// This file is auto-generated.
// Do not edit manually - run 'npm run icons' to regenerate
// Import only the icons you need for optimal bundle size (tree-shakeable).

import { createIconWrapper } from '@/components/Icon/Icon';
import AiIconRaw from './ai.svg?react';
import ArrowCornerIconRaw from './arrow-corner.svg?react';
import ArrowDownLeftIconRaw from './arrow-down-left.svg?react';
import ArrowDownRightIconRaw from './arrow-down-right.svg?react';
import ArrowDownIconRaw from './arrow-down.svg?react';
import ArrowLeftIconRaw from './arrow-left.svg?react';
import ArrowRightIconRaw from './arrow-right.svg?react';
import ArrowUpLeftIconRaw from './arrow-up-left.svg?react';
import ArrowUpRightIconRaw from './arrow-up-right.svg?react';
import ArrowUpIconRaw from './arrow-up.svg?react';
import AudioWavesIconRaw from './audio-waves.svg?react';
import AutosIconRaw from './autos.svg?react';
import AvatarFilledIconRaw from './avatar-filled.svg?react';
import AvatarIconRaw from './avatar.svg?react';
import BookmarkFilledIconRaw from './bookmark-filled.svg?react';
import BookmarkIconRaw from './bookmark.svg?react';
import BusinessFilledIconRaw from './business-filled.svg?react';
import BusinessIconRaw from './business.svg?react';
import CalendarIconRaw from './calendar.svg?react';
import CameraFilledIconRaw from './camera-filled.svg?react';
import CameraIconRaw from './camera.svg?react';
import ChartIconRaw from './chart.svg?react';
import CheckIconRaw from './check.svg?react';
import CheckboxCheckedActiveIconRaw from './checkbox-checked-active.svg?react';
import CheckboxInactiveIconRaw from './checkbox-inactive.svg?react';
import ChevronDownIconRaw from './chevron-down.svg?react';
import ChevronLeftIconRaw from './chevron-left.svg?react';
import ChevronRightIconRaw from './chevron-right.svg?react';
import ChevronUpIconRaw from './chevron-up.svg?react';
import ClassifiedsFilledIconRaw from './classifieds-filled.svg?react';
import ClockIconRaw from './clock.svg?react';
import CloseIconRaw from './close.svg?react';
import CollapseIconRaw from './collapse.svg?react';
import CommentDisabledIconRaw from './comment-disabled.svg?react';
import CommentIconRaw from './comment.svg?react';
import CompanyLogoIconRaw from './company-logo.svg?react';
import CompanyNameIconRaw from './company-name.svg?react';
import ConnectIconRaw from './connect.svg?react';
import CopyIconRaw from './copy.svg?react';
import CornerDownLeftIconRaw from './corner-down-left.svg?react';
import CornerDownRightIconRaw from './corner-down-right.svg?react';
import CornerUpLeftIconRaw from './corner-up-left.svg?react';
import CornerUpRightIconRaw from './corner-up-right.svg?react';
import DeviceMobileIconRaw from './device-mobile.svg?react';
import DeviceIconRaw from './device.svg?react';
import DiamondIconRaw from './diamond.svg?react';
import DocumentIconRaw from './document.svg?react';
import DownloadIconRaw from './download.svg?react';
import EditIconRaw from './edit.svg?react';
import ErrorFilledIconRaw from './error-filled.svg?react';
import ErrorIconRaw from './error.svg?react';
import EventIconRaw from './event.svg?react';
import ExpandIconRaw from './expand.svg?react';
import FaqIconRaw from './faq.svg?react';
import FastForwardIconRaw from './fast-forward.svg?react';
import FilterIconRaw from './filter.svg?react';
import FireIconRaw from './fire.svg?react';
import FlagFilledIconRaw from './flag-filled.svg?react';
import FlagIconRaw from './flag.svg?react';
import ForwardFilledIconRaw from './forward-filled.svg?react';
import ForwardIconRaw from './forward.svg?react';
import GiftIconRaw from './gift.svg?react';
import HeadphonesFilledIconRaw from './headphones-filled.svg?react';
import HeadphonesIconRaw from './headphones.svg?react';
import HelpFilledIconRaw from './help-filled.svg?react';
import HelpIconRaw from './help.svg?react';
import HomeFilledIconRaw from './home-filled.svg?react';
import HomeIconRaw from './home.svg?react';
import ImageIconRaw from './image.svg?react';
import InformationFilledIconRaw from './information-filled.svg?react';
import InformationIconRaw from './information.svg?react';
import IosShareIconRaw from './ios-share.svg?react';
import JobsFilledIconRaw from './jobs-filled.svg?react';
import LatestIconRaw from './latest.svg?react';
import LinkIconRaw from './link.svg?react';
import Local01FilledIconRaw from './local-01-filled.svg?react';
import Local01IconRaw from './local-01.svg?react';
import Local02FilledIconRaw from './local-02-filled.svg?react';
import Local02IconRaw from './local-02.svg?react';
import LocationFilledIconRaw from './location-filled.svg?react';
import LocationIconRaw from './location.svg?react';
import LockFilledIconRaw from './lock-filled.svg?react';
import LockIconRaw from './lock.svg?react';
import LogOutIconRaw from './log-out.svg?react';
import MailIconRaw from './mail.svg?react';
import MaximizeIconRaw from './maximize.svg?react';
import MenuHorizontalIconRaw from './menu-horizontal.svg?react';
import MenuSearchIconRaw from './menu-search.svg?react';
import MenuStackedIconRaw from './menu-stacked.svg?react';
import MenuVerticalIconRaw from './menu-vertical.svg?react';
import MicrophoneFilledIconRaw from './microphone-filled.svg?react';
import MicrophoneIconRaw from './microphone.svg?react';
import MinimizeIconRaw from './minimize.svg?react';
import MinusIconRaw from './minus.svg?react';
import NewsIconRaw from './news.svg?react';
import NotificationFilledIconRaw from './notification-filled.svg?react';
import NotificationNewIconRaw from './notification-new.svg?react';
import NotificationOffIconRaw from './notification-off.svg?react';
import NotificationIconRaw from './notification.svg?react';
import ObituariesFilledIconRaw from './obituaries-filled.svg?react';
import ObituariesIconRaw from './obituaries.svg?react';
import OpinionFilledIconRaw from './opinion-filled.svg?react';
import OpinionIconRaw from './opinion.svg?react';
import PauseFilledIconRaw from './pause-filled.svg?react';
import PauseIconRaw from './pause.svg?react';
import PhoneIconRaw from './phone.svg?react';
import PhotoIconRaw from './photo.svg?react';
import PinnedIconRaw from './pinned.svg?react';
import PlayFilledIconRaw from './play-filled.svg?react';
import PlayIconRaw from './play.svg?react';
import PlusIconRaw from './plus.svg?react';
import PoliticsFilledIconRaw from './politics-filled.svg?react';
import PoliticsIconRaw from './politics.svg?react';
import PrintIconRaw from './print.svg?react';
import QuoteIconRaw from './quote.svg?react';
import RecentlyViewedIconRaw from './recently-viewed.svg?react';
import RedoIconRaw from './redo.svg?react';
import RefreshIconRaw from './refresh.svg?react';
import ReplyAllIconRaw from './reply-all.svg?react';
import ReplyIconRaw from './reply.svg?react';
import RewindIconRaw from './rewind.svg?react';
import ScrollIconRaw from './scroll.svg?react';
import SearchIconRaw from './search.svg?react';
import SectionFilledIconRaw from './section-filled.svg?react';
import SectionIconRaw from './section.svg?react';
import SendFilledIconRaw from './send-filled.svg?react';
import SendIconRaw from './send.svg?react';
import SettingsFilledIconRaw from './settings-filled.svg?react';
import SettingsIconRaw from './settings.svg?react';
import Share02IconRaw from './share-02.svg?react';
import ShareIconRaw from './share.svg?react';
import ShootingStarDownRightFilledIconRaw from './shooting-star-down-right-filled.svg?react';
import ShootingStarDownRightIconRaw from './shooting-star-down-right.svg?react';
import SocialFacebookCircleIconRaw from './social-facebook-circle.svg?react';
import SocialFacebookFullColorIconRaw from './social-facebook-full-color.svg?react';
import SocialFacebookIconRaw from './social-facebook.svg?react';
import SocialGoogleCircleIconRaw from './social-google-circle.svg?react';
import SocialGoogleFullColorIconRaw from './social-google-full-color.svg?react';
import SocialGoogleIconRaw from './social-google.svg?react';
import SocialInstagramCircleIconRaw from './social-instagram-circle.svg?react';
import SocialInstagramIconRaw from './social-instagram.svg?react';
import SocialLinkedinCircleIconRaw from './social-linkedin-circle.svg?react';
import SocialLinkedinFullColorIconRaw from './social-linkedin-full-color.svg?react';
import SocialLinkedinIconRaw from './social-linkedin.svg?react';
import SocialRedditCircleIconRaw from './social-reddit-circle.svg?react';
import SocialRedditFullColorIconRaw from './social-reddit-full-color.svg?react';
import SocialRedditIconRaw from './social-reddit.svg?react';
import SocialSpotifyCircleIconRaw from './social-spotify-circle.svg?react';
import SocialSpotifyFullColorIconRaw from './social-spotify-full-color.svg?react';
import SocialSpotifyIconRaw from './social-spotify.svg?react';
import SocialThreadsCircleIconRaw from './social-threads-circle.svg?react';
import SocialThreadsIconRaw from './social-threads.svg?react';
import SocialTiktokCircleIconRaw from './social-tiktok-circle.svg?react';
import SocialTiktokFullColorIconRaw from './social-tiktok-full-color.svg?react';
import SocialTiktokIconRaw from './social-tiktok.svg?react';
import SocialTumblrCircleIconRaw from './social-tumblr-circle.svg?react';
import SocialTumblrIconRaw from './social-tumblr.svg?react';
import SocialXCircleIconRaw from './social-x-circle.svg?react';
import SocialXIconRaw from './social-x.svg?react';
import SocialYoutubeCircleIconRaw from './social-youtube-circle.svg?react';
import SocialYoutubeFullColorIconRaw from './social-youtube-full-color.svg?react';
import SocialYoutubeIconRaw from './social-youtube.svg?react';
import SortDownIconRaw from './sort-down.svg?react';
import SortUpIconRaw from './sort-up.svg?react';
import SortIconRaw from './sort.svg?react';
import SpeechFilledIconRaw from './speech-filled.svg?react';
import SpeechIconRaw from './speech.svg?react';
import SponsoredIconRaw from './sponsored.svg?react';
import SportsBaseballIconRaw from './sports-baseball.svg?react';
import SportsBasketballIconRaw from './sports-basketball.svg?react';
import SportsCollegeIconRaw from './sports-college.svg?react';
import SportsFilledIconRaw from './sports-filled.svg?react';
import SportsFootballIconRaw from './sports-football.svg?react';
import SportsGolfIconRaw from './sports-golf.svg?react';
import SportsHighSchoolIconRaw from './sports-high-school.svg?react';
import SportsHockeyIconRaw from './sports-hockey.svg?react';
import SportsLeagueMlbColorIconRaw from './sports-league-mlb-color.svg?react';
import SportsLeagueMlsColorIconRaw from './sports-league-mls-color.svg?react';
import SportsLeagueNbaColorIconRaw from './sports-league-nba-color.svg?react';
import SportsLeagueNcaaColorIconRaw from './sports-league-ncaa-color.svg?react';
import SportsLeagueNflColorIconRaw from './sports-league-nfl-color.svg?react';
import SportsLeagueNhlColorIconRaw from './sports-league-nhl-color.svg?react';
import SportsLeaguePwhlColorIconRaw from './sports-league-pwhl-color.svg?react';
import SportsLeagueWnbaColorIconRaw from './sports-league-wnba-color.svg?react';
import SportsMotorsportIconRaw from './sports-motorsport.svg?react';
import SportsOutdoorIconRaw from './sports-outdoor.svg?react';
import SportsRosterFilledIconRaw from './sports-roster-filled.svg?react';
import SportsRosterIconRaw from './sports-roster.svg?react';
import SportsRunningIconRaw from './sports-running.svg?react';
import SportsScoresIconRaw from './sports-scores.svg?react';
import SportsSoccerIconRaw from './sports-soccer.svg?react';
import SportsStandingsIconRaw from './sports-standings.svg?react';
import SportsStatsIconRaw from './sports-stats.svg?react';
import SportsSwimmingIconRaw from './sports-swimming.svg?react';
import SportsTeamGophersIconRaw from './sports-team-gophers.svg?react';
import SportsTeamLoonsIconRaw from './sports-team-loons.svg?react';
import SportsTeamTwinsIconRaw from './sports-team-twins.svg?react';
import SportsTeamVikingsIconRaw from './sports-team-vikings.svg?react';
import SportsTeamWildIconRaw from './sports-team-wild.svg?react';
import SportsTeamWolvesIconRaw from './sports-team-wolves.svg?react';
import SportsTennisBallIconRaw from './sports-tennis-ball.svg?react';
import SportsTennisIconRaw from './sports-tennis.svg?react';
import SportsTrophyIconRaw from './sports-trophy.svg?react';
import SportsVolleyballIconRaw from './sports-volleyball.svg?react';
import SportsIconRaw from './sports.svg?react';
import StarFilledIconRaw from './star-filled.svg?react';
import StarIconRaw from './star.svg?react';
import SteeringWheelIconRaw from './steering-wheel.svg?react';
import SuccessIconRaw from './success.svg?react';
import TextSizeIconRaw from './text-size.svg?react';
import ThumbsDownFilledIconRaw from './thumbs-down-filled.svg?react';
import ThumbsDownIconRaw from './thumbs-down.svg?react';
import ThumbsUpFilledIconRaw from './thumbs-up-filled.svg?react';
import ThumbsUpIconRaw from './thumbs-up.svg?react';
import TicketIconRaw from './ticket.svg?react';
import TombstoneFilledIconRaw from './tombstone-filled.svg?react';
import TombstoneIconRaw from './tombstone.svg?react';
import TrashIconRaw from './trash.svg?react';
import TrendingIconRaw from './trending.svg?react';
import UndoIconRaw from './undo.svg?react';
import UserIconRaw from './user.svg?react';
import Variety01FilledIconRaw from './variety-01-filled.svg?react';
import Variety01IconRaw from './variety-01.svg?react';
import Variety02FilledIconRaw from './variety-02-filled.svg?react';
import Variety02IconRaw from './variety-02.svg?react';
import VideoFilledIconRaw from './video-filled.svg?react';
import VideoIconRaw from './video.svg?react';
import ViewNextIconRaw from './view-next.svg?react';
import VolumeFilledIconRaw from './volume-filled.svg?react';
import VolumeMuteFilledIconRaw from './volume-mute-filled.svg?react';
import VolumeMuteIconRaw from './volume-mute.svg?react';
import VolumeIconRaw from './volume.svg?react';
import WarningIconRaw from './warning.svg?react';
import WeatherDayMostlyCloudyThunderstormsColorIconRaw from './weather-day-mostly-cloudy-thunderstorms-color.svg?react';
import WeatherDayMostlyCloudyThunderstormsIconRaw from './weather-day-mostly-cloudy-thunderstorms.svg?react';
import WeatherDayMostlySunnyColorIconRaw from './weather-day-mostly-sunny-color.svg?react';
import WeatherDayMostlySunnyIconRaw from './weather-day-mostly-sunny.svg?react';
import WeatherDayNightCloudyColorIconRaw from './weather-day-night-cloudy-color.svg?react';
import WeatherDayNightCloudyIconRaw from './weather-day-night-cloudy.svg?react';
import WeatherDayNightFlurriesColorIconRaw from './weather-day-night-flurries-color.svg?react';
import WeatherDayNightFlurriesIconRaw from './weather-day-night-flurries.svg?react';
import WeatherDayNightIceColorIconRaw from './weather-day-night-ice-color.svg?react';
import WeatherDayNightIceIconRaw from './weather-day-night-ice.svg?react';
import WeatherDayNightShowersColorIconRaw from './weather-day-night-showers-color.svg?react';
import WeatherDayNightShowersIconRaw from './weather-day-night-showers.svg?react';
import WeatherDayNightSleetColorIconRaw from './weather-day-night-sleet-color.svg?react';
import WeatherDayNightSleetIconRaw from './weather-day-night-sleet.svg?react';
import WeatherDayPartlySunnyColorIconRaw from './weather-day-partly-sunny-color.svg?react';
import WeatherDayPartlySunnyFlurriesColorIconRaw from './weather-day-partly-sunny-flurries-color.svg?react';
import WeatherDayPartlySunnyFlurriesIconRaw from './weather-day-partly-sunny-flurries.svg?react';
import WeatherDayPartlySunnyShowersColorIconRaw from './weather-day-partly-sunny-showers-color.svg?react';
import WeatherDayPartlySunnyShowersIconRaw from './weather-day-partly-sunny-showers.svg?react';
import WeatherDayPartlySunnyThunderstormsColorIconRaw from './weather-day-partly-sunny-thunderstorms-color.svg?react';
import WeatherDayPartlySunnyThunderstormsIconRaw from './weather-day-partly-sunny-thunderstorms.svg?react';
import WeatherDayPartlySunnyIconRaw from './weather-day-partly-sunny.svg?react';
import WeatherDaySunnyColorIconRaw from './weather-day-sunny-color.svg?react';
import WeatherDaySunnyIconRaw from './weather-day-sunny.svg?react';
import WeatherNightColorIconRaw from './weather-night-color.svg?react';
import WeatherNightMostlyCloudyColorIconRaw from './weather-night-mostly-cloudy-color.svg?react';
import WeatherNightMostlyCloudyIconRaw from './weather-night-mostly-cloudy.svg?react';
import WeatherNightPartlyCloudyColorIconRaw from './weather-night-partly-cloudy-color.svg?react';
import WeatherNightPartlyCloudyFlurriesColorIconRaw from './weather-night-partly-cloudy-flurries-color.svg?react';
import WeatherNightPartlyCloudyFlurriesIconRaw from './weather-night-partly-cloudy-flurries.svg?react';
import WeatherNightPartlyCloudyShowersColorIconRaw from './weather-night-partly-cloudy-showers-color.svg?react';
import WeatherNightPartlyCloudyShowersIconRaw from './weather-night-partly-cloudy-showers.svg?react';
import WeatherNightPartlyCloudyThunderstormsColorIconRaw from './weather-night-partly-cloudy-thunderstorms-color.svg?react';
import WeatherNightPartlyCloudyThunderstormsIconRaw from './weather-night-partly-cloudy-thunderstorms.svg?react';
import WeatherNightPartlyCloudyIconRaw from './weather-night-partly-cloudy.svg?react';
import WeatherNightSnowyColorIconRaw from './weather-night-snowy-color.svg?react';
import WeatherNightSnowyIconRaw from './weather-night-snowy.svg?react';
import WeatherNightWintryMixColorIconRaw from './weather-night-wintry-mix-color.svg?react';
import WeatherNightWintryMixIconRaw from './weather-night-wintry-mix.svg?react';
import WeatherNightIconRaw from './weather-night.svg?react';
import WebsiteIconRaw from './website.svg?react';
import WorldFilledIconRaw from './world-filled.svg?react';
import WorldIconRaw from './world.svg?react';
import ZoomInIconRaw from './zoom-in.svg?react';
import ZoomOutIconRaw from './zoom-out.svg?react';

export const AiIcon = createIconWrapper(AiIconRaw);
export const ArrowCornerIcon = createIconWrapper(ArrowCornerIconRaw);
export const ArrowDownLeftIcon = createIconWrapper(ArrowDownLeftIconRaw);
export const ArrowDownRightIcon = createIconWrapper(ArrowDownRightIconRaw);
export const ArrowDownIcon = createIconWrapper(ArrowDownIconRaw);
export const ArrowLeftIcon = createIconWrapper(ArrowLeftIconRaw);
export const ArrowRightIcon = createIconWrapper(ArrowRightIconRaw);
export const ArrowUpLeftIcon = createIconWrapper(ArrowUpLeftIconRaw);
export const ArrowUpRightIcon = createIconWrapper(ArrowUpRightIconRaw);
export const ArrowUpIcon = createIconWrapper(ArrowUpIconRaw);
export const AudioWavesIcon = createIconWrapper(AudioWavesIconRaw);
export const AutosIcon = createIconWrapper(AutosIconRaw);
export const AvatarFilledIcon = createIconWrapper(AvatarFilledIconRaw);
export const AvatarIcon = createIconWrapper(AvatarIconRaw);
export const BookmarkFilledIcon = createIconWrapper(BookmarkFilledIconRaw);
export const BookmarkIcon = createIconWrapper(BookmarkIconRaw);
export const BusinessFilledIcon = createIconWrapper(BusinessFilledIconRaw);
export const BusinessIcon = createIconWrapper(BusinessIconRaw);
export const CalendarIcon = createIconWrapper(CalendarIconRaw);
export const CameraFilledIcon = createIconWrapper(CameraFilledIconRaw);
export const CameraIcon = createIconWrapper(CameraIconRaw);
export const ChartIcon = createIconWrapper(ChartIconRaw);
export const CheckIcon = createIconWrapper(CheckIconRaw);
export const CheckboxCheckedActiveIcon = createIconWrapper(CheckboxCheckedActiveIconRaw);
export const CheckboxInactiveIcon = createIconWrapper(CheckboxInactiveIconRaw);
export const ChevronDownIcon = createIconWrapper(ChevronDownIconRaw);
export const ChevronLeftIcon = createIconWrapper(ChevronLeftIconRaw);
export const ChevronRightIcon = createIconWrapper(ChevronRightIconRaw);
export const ChevronUpIcon = createIconWrapper(ChevronUpIconRaw);
export const ClassifiedsFilledIcon = createIconWrapper(ClassifiedsFilledIconRaw);
export const ClockIcon = createIconWrapper(ClockIconRaw);
export const CloseIcon = createIconWrapper(CloseIconRaw);
export const CollapseIcon = createIconWrapper(CollapseIconRaw);
export const CommentDisabledIcon = createIconWrapper(CommentDisabledIconRaw);
export const CommentIcon = createIconWrapper(CommentIconRaw);
export const CompanyLogoIcon = createIconWrapper(CompanyLogoIconRaw);
export const CompanyNameIcon = createIconWrapper(CompanyNameIconRaw);
export const ConnectIcon = createIconWrapper(ConnectIconRaw);
export const CopyIcon = createIconWrapper(CopyIconRaw);
export const CornerDownLeftIcon = createIconWrapper(CornerDownLeftIconRaw);
export const CornerDownRightIcon = createIconWrapper(CornerDownRightIconRaw);
export const CornerUpLeftIcon = createIconWrapper(CornerUpLeftIconRaw);
export const CornerUpRightIcon = createIconWrapper(CornerUpRightIconRaw);
export const DeviceMobileIcon = createIconWrapper(DeviceMobileIconRaw);
export const DeviceIcon = createIconWrapper(DeviceIconRaw);
export const DiamondIcon = createIconWrapper(DiamondIconRaw);
export const DocumentIcon = createIconWrapper(DocumentIconRaw);
export const DownloadIcon = createIconWrapper(DownloadIconRaw);
export const EditIcon = createIconWrapper(EditIconRaw);
export const ErrorFilledIcon = createIconWrapper(ErrorFilledIconRaw);
export const ErrorIcon = createIconWrapper(ErrorIconRaw);
export const EventIcon = createIconWrapper(EventIconRaw);
export const ExpandIcon = createIconWrapper(ExpandIconRaw);
export const FaqIcon = createIconWrapper(FaqIconRaw);
export const FastForwardIcon = createIconWrapper(FastForwardIconRaw);
export const FilterIcon = createIconWrapper(FilterIconRaw);
export const FireIcon = createIconWrapper(FireIconRaw);
export const FlagFilledIcon = createIconWrapper(FlagFilledIconRaw);
export const FlagIcon = createIconWrapper(FlagIconRaw);
export const ForwardFilledIcon = createIconWrapper(ForwardFilledIconRaw);
export const ForwardIcon = createIconWrapper(ForwardIconRaw);
export const GiftIcon = createIconWrapper(GiftIconRaw);
export const HeadphonesFilledIcon = createIconWrapper(HeadphonesFilledIconRaw);
export const HeadphonesIcon = createIconWrapper(HeadphonesIconRaw);
export const HelpFilledIcon = createIconWrapper(HelpFilledIconRaw);
export const HelpIcon = createIconWrapper(HelpIconRaw);
export const HomeFilledIcon = createIconWrapper(HomeFilledIconRaw);
export const HomeIcon = createIconWrapper(HomeIconRaw);
export const ImageIcon = createIconWrapper(ImageIconRaw);
export const InformationFilledIcon = createIconWrapper(InformationFilledIconRaw);
export const InformationIcon = createIconWrapper(InformationIconRaw);
export const IosShareIcon = createIconWrapper(IosShareIconRaw);
export const JobsFilledIcon = createIconWrapper(JobsFilledIconRaw);
export const LatestIcon = createIconWrapper(LatestIconRaw);
export const LinkIcon = createIconWrapper(LinkIconRaw);
export const Local01FilledIcon = createIconWrapper(Local01FilledIconRaw);
export const Local01Icon = createIconWrapper(Local01IconRaw);
export const Local02FilledIcon = createIconWrapper(Local02FilledIconRaw);
export const Local02Icon = createIconWrapper(Local02IconRaw);
export const LocationFilledIcon = createIconWrapper(LocationFilledIconRaw);
export const LocationIcon = createIconWrapper(LocationIconRaw);
export const LockFilledIcon = createIconWrapper(LockFilledIconRaw);
export const LockIcon = createIconWrapper(LockIconRaw);
export const LogOutIcon = createIconWrapper(LogOutIconRaw);
export const MailIcon = createIconWrapper(MailIconRaw);
export const MaximizeIcon = createIconWrapper(MaximizeIconRaw);
export const MenuHorizontalIcon = createIconWrapper(MenuHorizontalIconRaw);
export const MenuSearchIcon = createIconWrapper(MenuSearchIconRaw);
export const MenuStackedIcon = createIconWrapper(MenuStackedIconRaw);
export const MenuVerticalIcon = createIconWrapper(MenuVerticalIconRaw);
export const MicrophoneFilledIcon = createIconWrapper(MicrophoneFilledIconRaw);
export const MicrophoneIcon = createIconWrapper(MicrophoneIconRaw);
export const MinimizeIcon = createIconWrapper(MinimizeIconRaw);
export const MinusIcon = createIconWrapper(MinusIconRaw);
export const NewsIcon = createIconWrapper(NewsIconRaw);
export const NotificationFilledIcon = createIconWrapper(NotificationFilledIconRaw);
export const NotificationNewIcon = createIconWrapper(NotificationNewIconRaw);
export const NotificationOffIcon = createIconWrapper(NotificationOffIconRaw);
export const NotificationIcon = createIconWrapper(NotificationIconRaw);
export const ObituariesFilledIcon = createIconWrapper(ObituariesFilledIconRaw);
export const ObituariesIcon = createIconWrapper(ObituariesIconRaw);
export const OpinionFilledIcon = createIconWrapper(OpinionFilledIconRaw);
export const OpinionIcon = createIconWrapper(OpinionIconRaw);
export const PauseFilledIcon = createIconWrapper(PauseFilledIconRaw);
export const PauseIcon = createIconWrapper(PauseIconRaw);
export const PhoneIcon = createIconWrapper(PhoneIconRaw);
export const PhotoIcon = createIconWrapper(PhotoIconRaw);
export const PinnedIcon = createIconWrapper(PinnedIconRaw);
export const PlayFilledIcon = createIconWrapper(PlayFilledIconRaw);
export const PlayIcon = createIconWrapper(PlayIconRaw);
export const PlusIcon = createIconWrapper(PlusIconRaw);
export const PoliticsFilledIcon = createIconWrapper(PoliticsFilledIconRaw);
export const PoliticsIcon = createIconWrapper(PoliticsIconRaw);
export const PrintIcon = createIconWrapper(PrintIconRaw);
export const QuoteIcon = createIconWrapper(QuoteIconRaw);
export const RecentlyViewedIcon = createIconWrapper(RecentlyViewedIconRaw);
export const RedoIcon = createIconWrapper(RedoIconRaw);
export const RefreshIcon = createIconWrapper(RefreshIconRaw);
export const ReplyAllIcon = createIconWrapper(ReplyAllIconRaw);
export const ReplyIcon = createIconWrapper(ReplyIconRaw);
export const RewindIcon = createIconWrapper(RewindIconRaw);
export const ScrollIcon = createIconWrapper(ScrollIconRaw);
export const SearchIcon = createIconWrapper(SearchIconRaw);
export const SectionFilledIcon = createIconWrapper(SectionFilledIconRaw);
export const SectionIcon = createIconWrapper(SectionIconRaw);
export const SendFilledIcon = createIconWrapper(SendFilledIconRaw);
export const SendIcon = createIconWrapper(SendIconRaw);
export const SettingsFilledIcon = createIconWrapper(SettingsFilledIconRaw);
export const SettingsIcon = createIconWrapper(SettingsIconRaw);
export const Share02Icon = createIconWrapper(Share02IconRaw);
export const ShareIcon = createIconWrapper(ShareIconRaw);
export const ShootingStarDownRightFilledIcon = createIconWrapper(
  ShootingStarDownRightFilledIconRaw
);
export const ShootingStarDownRightIcon = createIconWrapper(ShootingStarDownRightIconRaw);
export const SocialFacebookCircleIcon = createIconWrapper(SocialFacebookCircleIconRaw);
export const SocialFacebookFullColorIcon = createIconWrapper(SocialFacebookFullColorIconRaw);
export const SocialFacebookIcon = createIconWrapper(SocialFacebookIconRaw);
export const SocialGoogleCircleIcon = createIconWrapper(SocialGoogleCircleIconRaw);
export const SocialGoogleFullColorIcon = createIconWrapper(SocialGoogleFullColorIconRaw);
export const SocialGoogleIcon = createIconWrapper(SocialGoogleIconRaw);
export const SocialInstagramCircleIcon = createIconWrapper(SocialInstagramCircleIconRaw);
export const SocialInstagramIcon = createIconWrapper(SocialInstagramIconRaw);
export const SocialLinkedinCircleIcon = createIconWrapper(SocialLinkedinCircleIconRaw);
export const SocialLinkedinFullColorIcon = createIconWrapper(SocialLinkedinFullColorIconRaw);
export const SocialLinkedinIcon = createIconWrapper(SocialLinkedinIconRaw);
export const SocialRedditCircleIcon = createIconWrapper(SocialRedditCircleIconRaw);
export const SocialRedditFullColorIcon = createIconWrapper(SocialRedditFullColorIconRaw);
export const SocialRedditIcon = createIconWrapper(SocialRedditIconRaw);
export const SocialSpotifyCircleIcon = createIconWrapper(SocialSpotifyCircleIconRaw);
export const SocialSpotifyFullColorIcon = createIconWrapper(SocialSpotifyFullColorIconRaw);
export const SocialSpotifyIcon = createIconWrapper(SocialSpotifyIconRaw);
export const SocialThreadsCircleIcon = createIconWrapper(SocialThreadsCircleIconRaw);
export const SocialThreadsIcon = createIconWrapper(SocialThreadsIconRaw);
export const SocialTiktokCircleIcon = createIconWrapper(SocialTiktokCircleIconRaw);
export const SocialTiktokFullColorIcon = createIconWrapper(SocialTiktokFullColorIconRaw);
export const SocialTiktokIcon = createIconWrapper(SocialTiktokIconRaw);
export const SocialTumblrCircleIcon = createIconWrapper(SocialTumblrCircleIconRaw);
export const SocialTumblrIcon = createIconWrapper(SocialTumblrIconRaw);
export const SocialXCircleIcon = createIconWrapper(SocialXCircleIconRaw);
export const SocialXIcon = createIconWrapper(SocialXIconRaw);
export const SocialYoutubeCircleIcon = createIconWrapper(SocialYoutubeCircleIconRaw);
export const SocialYoutubeFullColorIcon = createIconWrapper(SocialYoutubeFullColorIconRaw);
export const SocialYoutubeIcon = createIconWrapper(SocialYoutubeIconRaw);
export const SortDownIcon = createIconWrapper(SortDownIconRaw);
export const SortUpIcon = createIconWrapper(SortUpIconRaw);
export const SortIcon = createIconWrapper(SortIconRaw);
export const SpeechFilledIcon = createIconWrapper(SpeechFilledIconRaw);
export const SpeechIcon = createIconWrapper(SpeechIconRaw);
export const SponsoredIcon = createIconWrapper(SponsoredIconRaw);
export const SportsBaseballIcon = createIconWrapper(SportsBaseballIconRaw);
export const SportsBasketballIcon = createIconWrapper(SportsBasketballIconRaw);
export const SportsCollegeIcon = createIconWrapper(SportsCollegeIconRaw);
export const SportsFilledIcon = createIconWrapper(SportsFilledIconRaw);
export const SportsFootballIcon = createIconWrapper(SportsFootballIconRaw);
export const SportsGolfIcon = createIconWrapper(SportsGolfIconRaw);
export const SportsHighSchoolIcon = createIconWrapper(SportsHighSchoolIconRaw);
export const SportsHockeyIcon = createIconWrapper(SportsHockeyIconRaw);
export const SportsLeagueMlbColorIcon = createIconWrapper(SportsLeagueMlbColorIconRaw);
export const SportsLeagueMlsColorIcon = createIconWrapper(SportsLeagueMlsColorIconRaw);
export const SportsLeagueNbaColorIcon = createIconWrapper(SportsLeagueNbaColorIconRaw);
export const SportsLeagueNcaaColorIcon = createIconWrapper(SportsLeagueNcaaColorIconRaw);
export const SportsLeagueNflColorIcon = createIconWrapper(SportsLeagueNflColorIconRaw);
export const SportsLeagueNhlColorIcon = createIconWrapper(SportsLeagueNhlColorIconRaw);
export const SportsLeaguePwhlColorIcon = createIconWrapper(SportsLeaguePwhlColorIconRaw);
export const SportsLeagueWnbaColorIcon = createIconWrapper(SportsLeagueWnbaColorIconRaw);
export const SportsMotorsportIcon = createIconWrapper(SportsMotorsportIconRaw);
export const SportsOutdoorIcon = createIconWrapper(SportsOutdoorIconRaw);
export const SportsRosterFilledIcon = createIconWrapper(SportsRosterFilledIconRaw);
export const SportsRosterIcon = createIconWrapper(SportsRosterIconRaw);
export const SportsRunningIcon = createIconWrapper(SportsRunningIconRaw);
export const SportsScoresIcon = createIconWrapper(SportsScoresIconRaw);
export const SportsSoccerIcon = createIconWrapper(SportsSoccerIconRaw);
export const SportsStandingsIcon = createIconWrapper(SportsStandingsIconRaw);
export const SportsStatsIcon = createIconWrapper(SportsStatsIconRaw);
export const SportsSwimmingIcon = createIconWrapper(SportsSwimmingIconRaw);
export const SportsTeamGophersIcon = createIconWrapper(SportsTeamGophersIconRaw);
export const SportsTeamLoonsIcon = createIconWrapper(SportsTeamLoonsIconRaw);
export const SportsTeamTwinsIcon = createIconWrapper(SportsTeamTwinsIconRaw);
export const SportsTeamVikingsIcon = createIconWrapper(SportsTeamVikingsIconRaw);
export const SportsTeamWildIcon = createIconWrapper(SportsTeamWildIconRaw);
export const SportsTeamWolvesIcon = createIconWrapper(SportsTeamWolvesIconRaw);
export const SportsTennisBallIcon = createIconWrapper(SportsTennisBallIconRaw);
export const SportsTennisIcon = createIconWrapper(SportsTennisIconRaw);
export const SportsTrophyIcon = createIconWrapper(SportsTrophyIconRaw);
export const SportsVolleyballIcon = createIconWrapper(SportsVolleyballIconRaw);
export const SportsIcon = createIconWrapper(SportsIconRaw);
export const StarFilledIcon = createIconWrapper(StarFilledIconRaw);
export const StarIcon = createIconWrapper(StarIconRaw);
export const SteeringWheelIcon = createIconWrapper(SteeringWheelIconRaw);
export const SuccessIcon = createIconWrapper(SuccessIconRaw);
export const TextSizeIcon = createIconWrapper(TextSizeIconRaw);
export const ThumbsDownFilledIcon = createIconWrapper(ThumbsDownFilledIconRaw);
export const ThumbsDownIcon = createIconWrapper(ThumbsDownIconRaw);
export const ThumbsUpFilledIcon = createIconWrapper(ThumbsUpFilledIconRaw);
export const ThumbsUpIcon = createIconWrapper(ThumbsUpIconRaw);
export const TicketIcon = createIconWrapper(TicketIconRaw);
export const TombstoneFilledIcon = createIconWrapper(TombstoneFilledIconRaw);
export const TombstoneIcon = createIconWrapper(TombstoneIconRaw);
export const TrashIcon = createIconWrapper(TrashIconRaw);
export const TrendingIcon = createIconWrapper(TrendingIconRaw);
export const UndoIcon = createIconWrapper(UndoIconRaw);
export const UserIcon = createIconWrapper(UserIconRaw);
export const Variety01FilledIcon = createIconWrapper(Variety01FilledIconRaw);
export const Variety01Icon = createIconWrapper(Variety01IconRaw);
export const Variety02FilledIcon = createIconWrapper(Variety02FilledIconRaw);
export const Variety02Icon = createIconWrapper(Variety02IconRaw);
export const VideoFilledIcon = createIconWrapper(VideoFilledIconRaw);
export const VideoIcon = createIconWrapper(VideoIconRaw);
export const ViewNextIcon = createIconWrapper(ViewNextIconRaw);
export const VolumeFilledIcon = createIconWrapper(VolumeFilledIconRaw);
export const VolumeMuteFilledIcon = createIconWrapper(VolumeMuteFilledIconRaw);
export const VolumeMuteIcon = createIconWrapper(VolumeMuteIconRaw);
export const VolumeIcon = createIconWrapper(VolumeIconRaw);
export const WarningIcon = createIconWrapper(WarningIconRaw);
export const WeatherDayMostlyCloudyThunderstormsColorIcon = createIconWrapper(
  WeatherDayMostlyCloudyThunderstormsColorIconRaw
);
export const WeatherDayMostlyCloudyThunderstormsIcon = createIconWrapper(
  WeatherDayMostlyCloudyThunderstormsIconRaw
);
export const WeatherDayMostlySunnyColorIcon = createIconWrapper(WeatherDayMostlySunnyColorIconRaw);
export const WeatherDayMostlySunnyIcon = createIconWrapper(WeatherDayMostlySunnyIconRaw);
export const WeatherDayNightCloudyColorIcon = createIconWrapper(WeatherDayNightCloudyColorIconRaw);
export const WeatherDayNightCloudyIcon = createIconWrapper(WeatherDayNightCloudyIconRaw);
export const WeatherDayNightFlurriesColorIcon = createIconWrapper(
  WeatherDayNightFlurriesColorIconRaw
);
export const WeatherDayNightFlurriesIcon = createIconWrapper(WeatherDayNightFlurriesIconRaw);
export const WeatherDayNightIceColorIcon = createIconWrapper(WeatherDayNightIceColorIconRaw);
export const WeatherDayNightIceIcon = createIconWrapper(WeatherDayNightIceIconRaw);
export const WeatherDayNightShowersColorIcon = createIconWrapper(
  WeatherDayNightShowersColorIconRaw
);
export const WeatherDayNightShowersIcon = createIconWrapper(WeatherDayNightShowersIconRaw);
export const WeatherDayNightSleetColorIcon = createIconWrapper(WeatherDayNightSleetColorIconRaw);
export const WeatherDayNightSleetIcon = createIconWrapper(WeatherDayNightSleetIconRaw);
export const WeatherDayPartlySunnyColorIcon = createIconWrapper(WeatherDayPartlySunnyColorIconRaw);
export const WeatherDayPartlySunnyFlurriesColorIcon = createIconWrapper(
  WeatherDayPartlySunnyFlurriesColorIconRaw
);
export const WeatherDayPartlySunnyFlurriesIcon = createIconWrapper(
  WeatherDayPartlySunnyFlurriesIconRaw
);
export const WeatherDayPartlySunnyShowersColorIcon = createIconWrapper(
  WeatherDayPartlySunnyShowersColorIconRaw
);
export const WeatherDayPartlySunnyShowersIcon = createIconWrapper(
  WeatherDayPartlySunnyShowersIconRaw
);
export const WeatherDayPartlySunnyThunderstormsColorIcon = createIconWrapper(
  WeatherDayPartlySunnyThunderstormsColorIconRaw
);
export const WeatherDayPartlySunnyThunderstormsIcon = createIconWrapper(
  WeatherDayPartlySunnyThunderstormsIconRaw
);
export const WeatherDayPartlySunnyIcon = createIconWrapper(WeatherDayPartlySunnyIconRaw);
export const WeatherDaySunnyColorIcon = createIconWrapper(WeatherDaySunnyColorIconRaw);
export const WeatherDaySunnyIcon = createIconWrapper(WeatherDaySunnyIconRaw);
export const WeatherNightColorIcon = createIconWrapper(WeatherNightColorIconRaw);
export const WeatherNightMostlyCloudyColorIcon = createIconWrapper(
  WeatherNightMostlyCloudyColorIconRaw
);
export const WeatherNightMostlyCloudyIcon = createIconWrapper(WeatherNightMostlyCloudyIconRaw);
export const WeatherNightPartlyCloudyColorIcon = createIconWrapper(
  WeatherNightPartlyCloudyColorIconRaw
);
export const WeatherNightPartlyCloudyFlurriesColorIcon = createIconWrapper(
  WeatherNightPartlyCloudyFlurriesColorIconRaw
);
export const WeatherNightPartlyCloudyFlurriesIcon = createIconWrapper(
  WeatherNightPartlyCloudyFlurriesIconRaw
);
export const WeatherNightPartlyCloudyShowersColorIcon = createIconWrapper(
  WeatherNightPartlyCloudyShowersColorIconRaw
);
export const WeatherNightPartlyCloudyShowersIcon = createIconWrapper(
  WeatherNightPartlyCloudyShowersIconRaw
);
export const WeatherNightPartlyCloudyThunderstormsColorIcon = createIconWrapper(
  WeatherNightPartlyCloudyThunderstormsColorIconRaw
);
export const WeatherNightPartlyCloudyThunderstormsIcon = createIconWrapper(
  WeatherNightPartlyCloudyThunderstormsIconRaw
);
export const WeatherNightPartlyCloudyIcon = createIconWrapper(WeatherNightPartlyCloudyIconRaw);
export const WeatherNightSnowyColorIcon = createIconWrapper(WeatherNightSnowyColorIconRaw);
export const WeatherNightSnowyIcon = createIconWrapper(WeatherNightSnowyIconRaw);
export const WeatherNightWintryMixColorIcon = createIconWrapper(WeatherNightWintryMixColorIconRaw);
export const WeatherNightWintryMixIcon = createIconWrapper(WeatherNightWintryMixIconRaw);
export const WeatherNightIcon = createIconWrapper(WeatherNightIconRaw);
export const WebsiteIcon = createIconWrapper(WebsiteIconRaw);
export const WorldFilledIcon = createIconWrapper(WorldFilledIconRaw);
export const WorldIcon = createIconWrapper(WorldIconRaw);
export const ZoomInIcon = createIconWrapper(ZoomInIconRaw);
export const ZoomOutIcon = createIconWrapper(ZoomOutIconRaw);

export type { IconWrapperProps, IconSize, IconColor } from '@/components/Icon/Icon.types';
