nodeLinker: node-modules
npmPublishRegistry: 'https://npm.pkg.github.com'

injectEnvironmentFiles:
  - .env?
  - .env.local?

npmScopes:
  minneapolisstartribune:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN}"
