/**
 * Type declaration for the generated storybook.requires module.
 * The actual file is generated by Metro's withStorybook when the dev server runs.
 */
declare module './storybook.requires' {
  import type { View } from '@storybook/react-native';
  export const view: View;
}
export {};
