import { useContext, useMemo } from 'react';
import { DesignSystemContext } from '@/providers/DesignSystemContext';
import type { Brand, ColorScheme } from '@/providers/theme-helpers';
import { createDesignSystemError } from '@/utils/errorPrefix';

// Token imports — generated by `yarn tokens`, resolved at build time via Vite aliases.
// Types are auto-generated with exact property names for autocomplete and typo detection.
import startribuneLightTheme from '@mobile/themes/startribune-light.js';
import startribuneDarkTheme from '@mobile/themes/startribune-dark.js';
import varsityLightTheme from '@mobile/themes/varsity-light.js';
import varsityDarkTheme from '@mobile/themes/varsity-dark.js';
import startribuneTypography from '@mobile/typography/startribune-typography.js';
import varsityTypography from '@mobile/typography/varsity-typography.js';

type BaseThemeTokens =
  | typeof startribuneLightTheme
  | typeof startribuneDarkTheme
  | typeof varsityLightTheme
  | typeof varsityDarkTheme;

type TypographyTokens = typeof startribuneTypography | typeof varsityTypography;

// Theme type: base tokens + typography, all with exact property names.
// Auto-generated types give autocomplete and compile-time typo detection.
type ThemeTokens = BaseThemeTokens & TypographyTokens;

/**
 * Hook to access native design tokens (brand, color scheme, and theme tokens).
 *
 * @returns Object containing brand, colorScheme, and theme tokens
 *
 * @example
 * ```tsx
 * import { useNativeTokens } from '@minneapolisstartribune/design-system/native';
 *
 * function MyComponent() {
 *   const { theme } = useNativeTokens();
 *
 *   // Use semantic tokens
 *   const borderRadius = theme.semanticPhotoLayoutBorderRadius;
 *
 *   return (
 *     <View style={{ borderRadius }}>
 *       <Text>Hello World</Text>
 *     </View>
 *   );
 * }
 * ```
 */
export function useNativeTokens(): {
  brand: Brand;
  colorScheme: ColorScheme;
  theme: ThemeTokens;
} {
  const ctx = useContext(DesignSystemContext);

  if (!ctx) {
    throw new Error(
      createDesignSystemError('useNativeTokens', 'must be used within a DesignSystemProvider.')
    );
  }

  const { brand, colorScheme } = ctx;

  // Get theme tokens based on brand and color scheme, merged with typography
  const theme = useMemo(() => {
    const baseTheme =
      brand === 'startribune'
        ? colorScheme === 'light'
          ? startribuneLightTheme
          : startribuneDarkTheme
        : colorScheme === 'light'
          ? varsityLightTheme
          : varsityDarkTheme;

    const typography = brand === 'startribune' ? startribuneTypography : varsityTypography;

    return {
      ...baseTheme,
      ...typography,
    } as ThemeTokens;
  }, [brand, colorScheme]) as ThemeTokens;

  return {
    brand,
    colorScheme,
    theme,
  };
}
