// This file is auto-generated by scripts/build-icon-mapping.js
// Do not edit manually - run 'npm run build:icons' to regenerate

import React from 'react';
import aiComponent from '../../icons/ai.svg?react';
import arrow_cornerComponent from '../../icons/arrow-corner.svg?react';
import arrow_down_leftComponent from '../../icons/arrow-down-left.svg?react';
import arrow_down_rightComponent from '../../icons/arrow-down-right.svg?react';
import arrow_downComponent from '../../icons/arrow-down.svg?react';
import arrow_leftComponent from '../../icons/arrow-left.svg?react';
import arrow_rightComponent from '../../icons/arrow-right.svg?react';
import arrow_up_leftComponent from '../../icons/arrow-up-left.svg?react';
import arrow_up_rightComponent from '../../icons/arrow-up-right.svg?react';
import arrow_upComponent from '../../icons/arrow-up.svg?react';
import audio_wavesComponent from '../../icons/audio-waves.svg?react';
import autosComponent from '../../icons/autos.svg?react';
import avatar_filledComponent from '../../icons/avatar-filled.svg?react';
import avatarComponent from '../../icons/avatar.svg?react';
import bookmark_filledComponent from '../../icons/bookmark-filled.svg?react';
import bookmarkComponent from '../../icons/bookmark.svg?react';
import business_filledComponent from '../../icons/business-filled.svg?react';
import businessComponent from '../../icons/business.svg?react';
import calendarComponent from '../../icons/calendar.svg?react';
import camera_filledComponent from '../../icons/camera-filled.svg?react';
import cameraComponent from '../../icons/camera.svg?react';
import chartComponent from '../../icons/chart.svg?react';
import checkComponent from '../../icons/check.svg?react';
import checkbox_checked_activeComponent from '../../icons/checkbox-checked-active.svg?react';
import checkbox_inactiveComponent from '../../icons/checkbox-inactive.svg?react';
import chevron_downComponent from '../../icons/chevron-down.svg?react';
import chevron_leftComponent from '../../icons/chevron-left.svg?react';
import chevron_rightComponent from '../../icons/chevron-right.svg?react';
import chevron_upComponent from '../../icons/chevron-up.svg?react';
import classifieds_filledComponent from '../../icons/classifieds-filled.svg?react';
import clockComponent from '../../icons/clock.svg?react';
import closeComponent from '../../icons/close.svg?react';
import collapseComponent from '../../icons/collapse.svg?react';
import comment_disabledComponent from '../../icons/comment-disabled.svg?react';
import commentComponent from '../../icons/comment.svg?react';
import company_logoComponent from '../../icons/company-logo.svg?react';
import company_nameComponent from '../../icons/company-name.svg?react';
import connectComponent from '../../icons/connect.svg?react';
import copyComponent from '../../icons/copy.svg?react';
import corner_down_leftComponent from '../../icons/corner-down-left.svg?react';
import corner_down_rightComponent from '../../icons/corner-down-right.svg?react';
import corner_up_leftComponent from '../../icons/corner-up-left.svg?react';
import corner_up_rightComponent from '../../icons/corner-up-right.svg?react';
import device_mobileComponent from '../../icons/device-mobile.svg?react';
import deviceComponent from '../../icons/device.svg?react';
import diamondComponent from '../../icons/diamond.svg?react';
import documentComponent from '../../icons/document.svg?react';
import downloadComponent from '../../icons/download.svg?react';
import editComponent from '../../icons/edit.svg?react';
import error_filledComponent from '../../icons/error-filled.svg?react';
import errorComponent from '../../icons/error.svg?react';
import eventComponent from '../../icons/event.svg?react';
import expandComponent from '../../icons/expand.svg?react';
import faqComponent from '../../icons/faq.svg?react';
import fast_forwardComponent from '../../icons/fast-forward.svg?react';
import filterComponent from '../../icons/filter.svg?react';
import fireComponent from '../../icons/fire.svg?react';
import flag_filledComponent from '../../icons/flag-filled.svg?react';
import flagComponent from '../../icons/flag.svg?react';
import forward_filledComponent from '../../icons/forward-filled.svg?react';
import forwardComponent from '../../icons/forward.svg?react';
import giftComponent from '../../icons/gift.svg?react';
import headphones_filledComponent from '../../icons/headphones-filled.svg?react';
import headphonesComponent from '../../icons/headphones.svg?react';
import help_filledComponent from '../../icons/help-filled.svg?react';
import helpComponent from '../../icons/help.svg?react';
import home_filledComponent from '../../icons/home-filled.svg?react';
import homeComponent from '../../icons/home.svg?react';
import imageComponent from '../../icons/image.svg?react';
import information_filledComponent from '../../icons/information-filled.svg?react';
import informationComponent from '../../icons/information.svg?react';
import ios_shareComponent from '../../icons/ios-share.svg?react';
import jobs_filledComponent from '../../icons/jobs-filled.svg?react';
import latestComponent from '../../icons/latest.svg?react';
import linkComponent from '../../icons/link.svg?react';
import local_01_filledComponent from '../../icons/local-01-filled.svg?react';
import local_01Component from '../../icons/local-01.svg?react';
import local_02_filledComponent from '../../icons/local-02-filled.svg?react';
import local_02Component from '../../icons/local-02.svg?react';
import location_filledComponent from '../../icons/location-filled.svg?react';
import locationComponent from '../../icons/location.svg?react';
import lock_filledComponent from '../../icons/lock-filled.svg?react';
import lockComponent from '../../icons/lock.svg?react';
import log_outComponent from '../../icons/log-out.svg?react';
import mailComponent from '../../icons/mail.svg?react';
import maximizeComponent from '../../icons/maximize.svg?react';
import menu_horizontalComponent from '../../icons/menu-horizontal.svg?react';
import menu_searchComponent from '../../icons/menu-search.svg?react';
import menu_stackedComponent from '../../icons/menu-stacked.svg?react';
import menu_verticalComponent from '../../icons/menu-vertical.svg?react';
import microphone_filledComponent from '../../icons/microphone-filled.svg?react';
import microphoneComponent from '../../icons/microphone.svg?react';
import minimizeComponent from '../../icons/minimize.svg?react';
import minusComponent from '../../icons/minus.svg?react';
import newsComponent from '../../icons/news.svg?react';
import notification_filledComponent from '../../icons/notification-filled.svg?react';
import notification_newComponent from '../../icons/notification-new.svg?react';
import notification_offComponent from '../../icons/notification-off.svg?react';
import notificationComponent from '../../icons/notification.svg?react';
import obituaries_filledComponent from '../../icons/obituaries-filled.svg?react';
import obituariesComponent from '../../icons/obituaries.svg?react';
import opinion_filledComponent from '../../icons/opinion-filled.svg?react';
import opinionComponent from '../../icons/opinion.svg?react';
import pause_filledComponent from '../../icons/pause-filled.svg?react';
import pauseComponent from '../../icons/pause.svg?react';
import phoneComponent from '../../icons/phone.svg?react';
import photoComponent from '../../icons/photo.svg?react';
import pinnedComponent from '../../icons/pinned.svg?react';
import play_filledComponent from '../../icons/play-filled.svg?react';
import playComponent from '../../icons/play.svg?react';
import plusComponent from '../../icons/plus.svg?react';
import politics_filledComponent from '../../icons/politics-filled.svg?react';
import politicsComponent from '../../icons/politics.svg?react';
import printComponent from '../../icons/print.svg?react';
import quoteComponent from '../../icons/quote.svg?react';
import recently_viewedComponent from '../../icons/recently-viewed.svg?react';
import redoComponent from '../../icons/redo.svg?react';
import refreshComponent from '../../icons/refresh.svg?react';
import reply_allComponent from '../../icons/reply-all.svg?react';
import replyComponent from '../../icons/reply.svg?react';
import rewindComponent from '../../icons/rewind.svg?react';
import scrollComponent from '../../icons/scroll.svg?react';
import searchComponent from '../../icons/search.svg?react';
import section_filledComponent from '../../icons/section-filled.svg?react';
import sectionComponent from '../../icons/section.svg?react';
import send_filledComponent from '../../icons/send-filled.svg?react';
import sendComponent from '../../icons/send.svg?react';
import settings_filledComponent from '../../icons/settings-filled.svg?react';
import settingsComponent from '../../icons/settings.svg?react';
import shareComponent from '../../icons/share.svg?react';
import shooting_star_down_right_filledComponent from '../../icons/shooting-star-down-right-filled.svg?react';
import shooting_star_down_rightComponent from '../../icons/shooting-star-down-right.svg?react';
import social_facebook_circleComponent from '../../icons/social-facebook-circle.svg?react';
import social_facebook_full_colorComponent from '../../icons/social-facebook-full-color.svg?react';
import social_facebookComponent from '../../icons/social-facebook.svg?react';
import social_google_circleComponent from '../../icons/social-google-circle.svg?react';
import social_google_full_colorComponent from '../../icons/social-google-full-color.svg?react';
import social_googleComponent from '../../icons/social-google.svg?react';
import social_instagram_circleComponent from '../../icons/social-instagram-circle.svg?react';
import social_instagramComponent from '../../icons/social-instagram.svg?react';
import social_linkedin_circleComponent from '../../icons/social-linkedin-circle.svg?react';
import social_linkedin_full_colorComponent from '../../icons/social-linkedin-full-color.svg?react';
import social_linkedinComponent from '../../icons/social-linkedin.svg?react';
import social_reddit_circleComponent from '../../icons/social-reddit-circle.svg?react';
import social_reddit_full_colorComponent from '../../icons/social-reddit-full-color.svg?react';
import social_redditComponent from '../../icons/social-reddit.svg?react';
import social_spotify_circleComponent from '../../icons/social-spotify-circle.svg?react';
import social_spotify_full_colorComponent from '../../icons/social-spotify-full-color.svg?react';
import social_spotifyComponent from '../../icons/social-spotify.svg?react';
import social_threads_circleComponent from '../../icons/social-threads-circle.svg?react';
import social_threadsComponent from '../../icons/social-threads.svg?react';
import social_tiktok_circleComponent from '../../icons/social-tiktok-circle.svg?react';
import social_tiktok_full_colorComponent from '../../icons/social-tiktok-full-color.svg?react';
import social_tiktokComponent from '../../icons/social-tiktok.svg?react';
import social_tumblr_circleComponent from '../../icons/social-tumblr-circle.svg?react';
import social_tumblrComponent from '../../icons/social-tumblr.svg?react';
import social_x_circleComponent from '../../icons/social-x-circle.svg?react';
import social_xComponent from '../../icons/social-x.svg?react';
import social_youtube_circleComponent from '../../icons/social-youtube-circle.svg?react';
import social_youtube_full_colorComponent from '../../icons/social-youtube-full-color.svg?react';
import social_youtubeComponent from '../../icons/social-youtube.svg?react';
import sort_downComponent from '../../icons/sort-down.svg?react';
import sort_upComponent from '../../icons/sort-up.svg?react';
import sortComponent from '../../icons/sort.svg?react';
import speech_filledComponent from '../../icons/speech-filled.svg?react';
import speechComponent from '../../icons/speech.svg?react';
import sponsoredComponent from '../../icons/sponsored.svg?react';
import sports_baseballComponent from '../../icons/sports-baseball.svg?react';
import sports_basketballComponent from '../../icons/sports-basketball.svg?react';
import sports_collegeComponent from '../../icons/sports-college.svg?react';
import sports_filledComponent from '../../icons/sports-filled.svg?react';
import sports_footballComponent from '../../icons/sports-football.svg?react';
import sports_golfComponent from '../../icons/sports-golf.svg?react';
import sports_high_schoolComponent from '../../icons/sports-high-school.svg?react';
import sports_hockeyComponent from '../../icons/sports-hockey.svg?react';
import sports_league_mlb_colorComponent from '../../icons/sports-league-mlb-color.svg?react';
import sports_league_mls_colorComponent from '../../icons/sports-league-mls-color.svg?react';
import sports_league_nba_colorComponent from '../../icons/sports-league-nba-color.svg?react';
import sports_league_ncaa_colorComponent from '../../icons/sports-league-ncaa-color.svg?react';
import sports_league_nfl_colorComponent from '../../icons/sports-league-nfl-color.svg?react';
import sports_league_nhl_colorComponent from '../../icons/sports-league-nhl-color.svg?react';
import sports_league_pwhl_colorComponent from '../../icons/sports-league-pwhl-color.svg?react';
import sports_league_wnba_colorComponent from '../../icons/sports-league-wnba-color.svg?react';
import sports_motorsportComponent from '../../icons/sports-motorsport.svg?react';
import sports_outdoorComponent from '../../icons/sports-outdoor.svg?react';
import sports_roster_filledComponent from '../../icons/sports-roster-filled.svg?react';
import sports_rosterComponent from '../../icons/sports-roster.svg?react';
import sports_runningComponent from '../../icons/sports-running.svg?react';
import sports_scoresComponent from '../../icons/sports-scores.svg?react';
import sports_soccerComponent from '../../icons/sports-soccer.svg?react';
import sports_standingsComponent from '../../icons/sports-standings.svg?react';
import sports_statsComponent from '../../icons/sports-stats.svg?react';
import sports_swimmingComponent from '../../icons/sports-swimming.svg?react';
import sports_team_gophersComponent from '../../icons/sports-team-gophers.svg?react';
import sports_team_loonsComponent from '../../icons/sports-team-loons.svg?react';
import sports_team_twinsComponent from '../../icons/sports-team-twins.svg?react';
import sports_team_vikingsComponent from '../../icons/sports-team-vikings.svg?react';
import sports_team_wildComponent from '../../icons/sports-team-wild.svg?react';
import sports_team_wolvesComponent from '../../icons/sports-team-wolves.svg?react';
import sports_tennis_ballComponent from '../../icons/sports-tennis-ball.svg?react';
import sports_tennisComponent from '../../icons/sports-tennis.svg?react';
import sports_trophyComponent from '../../icons/sports-trophy.svg?react';
import sports_volleyballComponent from '../../icons/sports-volleyball.svg?react';
import sportsComponent from '../../icons/sports.svg?react';
import star_filledComponent from '../../icons/star-filled.svg?react';
import starComponent from '../../icons/star.svg?react';
import steering_wheelComponent from '../../icons/steering-wheel.svg?react';
import text_sizeComponent from '../../icons/text-size.svg?react';
import thumbs_down_filledComponent from '../../icons/thumbs-down-filled.svg?react';
import thumbs_downComponent from '../../icons/thumbs-down.svg?react';
import thumbs_up_filledComponent from '../../icons/thumbs-up-filled.svg?react';
import thumbs_upComponent from '../../icons/thumbs-up.svg?react';
import ticketComponent from '../../icons/ticket.svg?react';
import tombstone_filledComponent from '../../icons/tombstone-filled.svg?react';
import tombstoneComponent from '../../icons/tombstone.svg?react';
import trashComponent from '../../icons/trash.svg?react';
import trendingComponent from '../../icons/trending.svg?react';
import undoComponent from '../../icons/undo.svg?react';
import userComponent from '../../icons/user.svg?react';
import variety_01_filledComponent from '../../icons/variety-01-filled.svg?react';
import variety_01Component from '../../icons/variety-01.svg?react';
import variety_02_filledComponent from '../../icons/variety-02-filled.svg?react';
import variety_02Component from '../../icons/variety-02.svg?react';
import video_filledComponent from '../../icons/video-filled.svg?react';
import videoComponent from '../../icons/video.svg?react';
import view_nextComponent from '../../icons/view-next.svg?react';
import volume_filledComponent from '../../icons/volume-filled.svg?react';
import volume_mute_filledComponent from '../../icons/volume-mute-filled.svg?react';
import volume_muteComponent from '../../icons/volume-mute.svg?react';
import volumeComponent from '../../icons/volume.svg?react';
import weather_day_mostly_cloudy_thunderstorms_colorComponent from '../../icons/weather-day-mostly-cloudy-thunderstorms-color.svg?react';
import weather_day_mostly_cloudy_thunderstormsComponent from '../../icons/weather-day-mostly-cloudy-thunderstorms.svg?react';
import weather_day_mostly_sunny_colorComponent from '../../icons/weather-day-mostly-sunny-color.svg?react';
import weather_day_mostly_sunnyComponent from '../../icons/weather-day-mostly-sunny.svg?react';
import weather_day_night_cloudy_colorComponent from '../../icons/weather-day-night-cloudy-color.svg?react';
import weather_day_night_cloudyComponent from '../../icons/weather-day-night-cloudy.svg?react';
import weather_day_night_flurries_colorComponent from '../../icons/weather-day-night-flurries-color.svg?react';
import weather_day_night_flurriesComponent from '../../icons/weather-day-night-flurries.svg?react';
import weather_day_night_ice_colorComponent from '../../icons/weather-day-night-ice-color.svg?react';
import weather_day_night_iceComponent from '../../icons/weather-day-night-ice.svg?react';
import weather_day_night_showers_colorComponent from '../../icons/weather-day-night-showers-color.svg?react';
import weather_day_night_showersComponent from '../../icons/weather-day-night-showers.svg?react';
import weather_day_night_sleet_colorComponent from '../../icons/weather-day-night-sleet-color.svg?react';
import weather_day_night_sleetComponent from '../../icons/weather-day-night-sleet.svg?react';
import weather_day_partly_sunny_colorComponent from '../../icons/weather-day-partly-sunny-color.svg?react';
import weather_day_partly_sunny_flurries_colorComponent from '../../icons/weather-day-partly-sunny-flurries-color.svg?react';
import weather_day_partly_sunny_flurriesComponent from '../../icons/weather-day-partly-sunny-flurries.svg?react';
import weather_day_partly_sunny_showers_colorComponent from '../../icons/weather-day-partly-sunny-showers-color.svg?react';
import weather_day_partly_sunny_showersComponent from '../../icons/weather-day-partly-sunny-showers.svg?react';
import weather_day_partly_sunny_thunderstorms_colorComponent from '../../icons/weather-day-partly-sunny-thunderstorms-color.svg?react';
import weather_day_partly_sunny_thunderstormsComponent from '../../icons/weather-day-partly-sunny-thunderstorms.svg?react';
import weather_day_partly_sunnyComponent from '../../icons/weather-day-partly-sunny.svg?react';
import weather_day_sunny_colorComponent from '../../icons/weather-day-sunny-color.svg?react';
import weather_day_sunnyComponent from '../../icons/weather-day-sunny.svg?react';
import weather_night_colorComponent from '../../icons/weather-night-color.svg?react';
import weather_night_mostly_cloudy_colorComponent from '../../icons/weather-night-mostly-cloudy-color.svg?react';
import weather_night_mostly_cloudyComponent from '../../icons/weather-night-mostly-cloudy.svg?react';
import weather_night_partly_cloudy_colorComponent from '../../icons/weather-night-partly-cloudy-color.svg?react';
import weather_night_partly_cloudy_flurries_colorComponent from '../../icons/weather-night-partly-cloudy-flurries-color.svg?react';
import weather_night_partly_cloudy_flurriesComponent from '../../icons/weather-night-partly-cloudy-flurries.svg?react';
import weather_night_partly_cloudy_showers_colorComponent from '../../icons/weather-night-partly-cloudy-showers-color.svg?react';
import weather_night_partly_cloudy_showersComponent from '../../icons/weather-night-partly-cloudy-showers.svg?react';
import weather_night_partly_cloudy_thunderstorms_colorComponent from '../../icons/weather-night-partly-cloudy-thunderstorms-color.svg?react';
import weather_night_partly_cloudy_thunderstormsComponent from '../../icons/weather-night-partly-cloudy-thunderstorms.svg?react';
import weather_night_partly_cloudyComponent from '../../icons/weather-night-partly-cloudy.svg?react';
import weather_night_snowy_colorComponent from '../../icons/weather-night-snowy-color.svg?react';
import weather_night_snowyComponent from '../../icons/weather-night-snowy.svg?react';
import weather_night_wintry_mix_colorComponent from '../../icons/weather-night-wintry-mix-color.svg?react';
import weather_night_wintry_mixComponent from '../../icons/weather-night-wintry-mix.svg?react';
import weather_nightComponent from '../../icons/weather-night.svg?react';
import websiteComponent from '../../icons/website.svg?react';
import world_filledComponent from '../../icons/world-filled.svg?react';
import worldComponent from '../../icons/world.svg?react';
import zoom_inComponent from '../../icons/zoom-in.svg?react';
import zoom_outComponent from '../../icons/zoom-out.svg?react';

export const iconOptions: Record<
  string,
  React.FC<React.SVGProps<SVGSVGElement> & { title?: string }>
> = {
  ai: aiComponent,
  'arrow-corner': arrow_cornerComponent,
  'arrow-down-left': arrow_down_leftComponent,
  'arrow-down-right': arrow_down_rightComponent,
  'arrow-down': arrow_downComponent,
  'arrow-left': arrow_leftComponent,
  'arrow-right': arrow_rightComponent,
  'arrow-up-left': arrow_up_leftComponent,
  'arrow-up-right': arrow_up_rightComponent,
  'arrow-up': arrow_upComponent,
  'audio-waves': audio_wavesComponent,
  autos: autosComponent,
  'avatar-filled': avatar_filledComponent,
  avatar: avatarComponent,
  'bookmark-filled': bookmark_filledComponent,
  bookmark: bookmarkComponent,
  'business-filled': business_filledComponent,
  business: businessComponent,
  calendar: calendarComponent,
  'camera-filled': camera_filledComponent,
  camera: cameraComponent,
  chart: chartComponent,
  check: checkComponent,
  'checkbox-checked-active': checkbox_checked_activeComponent,
  'checkbox-inactive': checkbox_inactiveComponent,
  'chevron-down': chevron_downComponent,
  'chevron-left': chevron_leftComponent,
  'chevron-right': chevron_rightComponent,
  'chevron-up': chevron_upComponent,
  'classifieds-filled': classifieds_filledComponent,
  clock: clockComponent,
  close: closeComponent,
  collapse: collapseComponent,
  'comment-disabled': comment_disabledComponent,
  comment: commentComponent,
  'company-logo': company_logoComponent,
  'company-name': company_nameComponent,
  connect: connectComponent,
  copy: copyComponent,
  'corner-down-left': corner_down_leftComponent,
  'corner-down-right': corner_down_rightComponent,
  'corner-up-left': corner_up_leftComponent,
  'corner-up-right': corner_up_rightComponent,
  'device-mobile': device_mobileComponent,
  device: deviceComponent,
  diamond: diamondComponent,
  document: documentComponent,
  download: downloadComponent,
  edit: editComponent,
  'error-filled': error_filledComponent,
  error: errorComponent,
  event: eventComponent,
  expand: expandComponent,
  faq: faqComponent,
  'fast-forward': fast_forwardComponent,
  filter: filterComponent,
  fire: fireComponent,
  'flag-filled': flag_filledComponent,
  flag: flagComponent,
  'forward-filled': forward_filledComponent,
  forward: forwardComponent,
  gift: giftComponent,
  'headphones-filled': headphones_filledComponent,
  headphones: headphonesComponent,
  'help-filled': help_filledComponent,
  help: helpComponent,
  'home-filled': home_filledComponent,
  home: homeComponent,
  image: imageComponent,
  'information-filled': information_filledComponent,
  information: informationComponent,
  'ios-share': ios_shareComponent,
  'jobs-filled': jobs_filledComponent,
  latest: latestComponent,
  link: linkComponent,
  'local-01-filled': local_01_filledComponent,
  'local-01': local_01Component,
  'local-02-filled': local_02_filledComponent,
  'local-02': local_02Component,
  'location-filled': location_filledComponent,
  location: locationComponent,
  'lock-filled': lock_filledComponent,
  lock: lockComponent,
  'log-out': log_outComponent,
  mail: mailComponent,
  maximize: maximizeComponent,
  'menu-horizontal': menu_horizontalComponent,
  'menu-search': menu_searchComponent,
  'menu-stacked': menu_stackedComponent,
  'menu-vertical': menu_verticalComponent,
  'microphone-filled': microphone_filledComponent,
  microphone: microphoneComponent,
  minimize: minimizeComponent,
  minus: minusComponent,
  news: newsComponent,
  'notification-filled': notification_filledComponent,
  'notification-new': notification_newComponent,
  'notification-off': notification_offComponent,
  notification: notificationComponent,
  'obituaries-filled': obituaries_filledComponent,
  obituaries: obituariesComponent,
  'opinion-filled': opinion_filledComponent,
  opinion: opinionComponent,
  'pause-filled': pause_filledComponent,
  pause: pauseComponent,
  phone: phoneComponent,
  photo: photoComponent,
  pinned: pinnedComponent,
  'play-filled': play_filledComponent,
  play: playComponent,
  plus: plusComponent,
  'politics-filled': politics_filledComponent,
  politics: politicsComponent,
  print: printComponent,
  quote: quoteComponent,
  'recently-viewed': recently_viewedComponent,
  redo: redoComponent,
  refresh: refreshComponent,
  'reply-all': reply_allComponent,
  reply: replyComponent,
  rewind: rewindComponent,
  scroll: scrollComponent,
  search: searchComponent,
  'section-filled': section_filledComponent,
  section: sectionComponent,
  'send-filled': send_filledComponent,
  send: sendComponent,
  'settings-filled': settings_filledComponent,
  settings: settingsComponent,
  share: shareComponent,
  'shooting-star-down-right-filled': shooting_star_down_right_filledComponent,
  'shooting-star-down-right': shooting_star_down_rightComponent,
  'social-facebook-circle': social_facebook_circleComponent,
  'social-facebook-full-color': social_facebook_full_colorComponent,
  'social-facebook': social_facebookComponent,
  'social-google-circle': social_google_circleComponent,
  'social-google-full-color': social_google_full_colorComponent,
  'social-google': social_googleComponent,
  'social-instagram-circle': social_instagram_circleComponent,
  'social-instagram': social_instagramComponent,
  'social-linkedin-circle': social_linkedin_circleComponent,
  'social-linkedin-full-color': social_linkedin_full_colorComponent,
  'social-linkedin': social_linkedinComponent,
  'social-reddit-circle': social_reddit_circleComponent,
  'social-reddit-full-color': social_reddit_full_colorComponent,
  'social-reddit': social_redditComponent,
  'social-spotify-circle': social_spotify_circleComponent,
  'social-spotify-full-color': social_spotify_full_colorComponent,
  'social-spotify': social_spotifyComponent,
  'social-threads-circle': social_threads_circleComponent,
  'social-threads': social_threadsComponent,
  'social-tiktok-circle': social_tiktok_circleComponent,
  'social-tiktok-full-color': social_tiktok_full_colorComponent,
  'social-tiktok': social_tiktokComponent,
  'social-tumblr-circle': social_tumblr_circleComponent,
  'social-tumblr': social_tumblrComponent,
  'social-x-circle': social_x_circleComponent,
  'social-x': social_xComponent,
  'social-youtube-circle': social_youtube_circleComponent,
  'social-youtube-full-color': social_youtube_full_colorComponent,
  'social-youtube': social_youtubeComponent,
  'sort-down': sort_downComponent,
  'sort-up': sort_upComponent,
  sort: sortComponent,
  'speech-filled': speech_filledComponent,
  speech: speechComponent,
  sponsored: sponsoredComponent,
  'sports-baseball': sports_baseballComponent,
  'sports-basketball': sports_basketballComponent,
  'sports-college': sports_collegeComponent,
  'sports-filled': sports_filledComponent,
  'sports-football': sports_footballComponent,
  'sports-golf': sports_golfComponent,
  'sports-high-school': sports_high_schoolComponent,
  'sports-hockey': sports_hockeyComponent,
  'sports-league-mlb-color': sports_league_mlb_colorComponent,
  'sports-league-mls-color': sports_league_mls_colorComponent,
  'sports-league-nba-color': sports_league_nba_colorComponent,
  'sports-league-ncaa-color': sports_league_ncaa_colorComponent,
  'sports-league-nfl-color': sports_league_nfl_colorComponent,
  'sports-league-nhl-color': sports_league_nhl_colorComponent,
  'sports-league-pwhl-color': sports_league_pwhl_colorComponent,
  'sports-league-wnba-color': sports_league_wnba_colorComponent,
  'sports-motorsport': sports_motorsportComponent,
  'sports-outdoor': sports_outdoorComponent,
  'sports-roster-filled': sports_roster_filledComponent,
  'sports-roster': sports_rosterComponent,
  'sports-running': sports_runningComponent,
  'sports-scores': sports_scoresComponent,
  'sports-soccer': sports_soccerComponent,
  'sports-standings': sports_standingsComponent,
  'sports-stats': sports_statsComponent,
  'sports-swimming': sports_swimmingComponent,
  'sports-team-gophers': sports_team_gophersComponent,
  'sports-team-loons': sports_team_loonsComponent,
  'sports-team-twins': sports_team_twinsComponent,
  'sports-team-vikings': sports_team_vikingsComponent,
  'sports-team-wild': sports_team_wildComponent,
  'sports-team-wolves': sports_team_wolvesComponent,
  'sports-tennis-ball': sports_tennis_ballComponent,
  'sports-tennis': sports_tennisComponent,
  'sports-trophy': sports_trophyComponent,
  'sports-volleyball': sports_volleyballComponent,
  sports: sportsComponent,
  'star-filled': star_filledComponent,
  star: starComponent,
  'steering-wheel': steering_wheelComponent,
  'text-size': text_sizeComponent,
  'thumbs-down-filled': thumbs_down_filledComponent,
  'thumbs-down': thumbs_downComponent,
  'thumbs-up-filled': thumbs_up_filledComponent,
  'thumbs-up': thumbs_upComponent,
  ticket: ticketComponent,
  'tombstone-filled': tombstone_filledComponent,
  tombstone: tombstoneComponent,
  trash: trashComponent,
  trending: trendingComponent,
  undo: undoComponent,
  user: userComponent,
  'variety-01-filled': variety_01_filledComponent,
  'variety-01': variety_01Component,
  'variety-02-filled': variety_02_filledComponent,
  'variety-02': variety_02Component,
  'video-filled': video_filledComponent,
  video: videoComponent,
  'view-next': view_nextComponent,
  'volume-filled': volume_filledComponent,
  'volume-mute-filled': volume_mute_filledComponent,
  'volume-mute': volume_muteComponent,
  volume: volumeComponent,
  'weather-day-mostly-cloudy-thunderstorms-color':
    weather_day_mostly_cloudy_thunderstorms_colorComponent,
  'weather-day-mostly-cloudy-thunderstorms': weather_day_mostly_cloudy_thunderstormsComponent,
  'weather-day-mostly-sunny-color': weather_day_mostly_sunny_colorComponent,
  'weather-day-mostly-sunny': weather_day_mostly_sunnyComponent,
  'weather-day-night-cloudy-color': weather_day_night_cloudy_colorComponent,
  'weather-day-night-cloudy': weather_day_night_cloudyComponent,
  'weather-day-night-flurries-color': weather_day_night_flurries_colorComponent,
  'weather-day-night-flurries': weather_day_night_flurriesComponent,
  'weather-day-night-ice-color': weather_day_night_ice_colorComponent,
  'weather-day-night-ice': weather_day_night_iceComponent,
  'weather-day-night-showers-color': weather_day_night_showers_colorComponent,
  'weather-day-night-showers': weather_day_night_showersComponent,
  'weather-day-night-sleet-color': weather_day_night_sleet_colorComponent,
  'weather-day-night-sleet': weather_day_night_sleetComponent,
  'weather-day-partly-sunny-color': weather_day_partly_sunny_colorComponent,
  'weather-day-partly-sunny-flurries-color': weather_day_partly_sunny_flurries_colorComponent,
  'weather-day-partly-sunny-flurries': weather_day_partly_sunny_flurriesComponent,
  'weather-day-partly-sunny-showers-color': weather_day_partly_sunny_showers_colorComponent,
  'weather-day-partly-sunny-showers': weather_day_partly_sunny_showersComponent,
  'weather-day-partly-sunny-thunderstorms-color':
    weather_day_partly_sunny_thunderstorms_colorComponent,
  'weather-day-partly-sunny-thunderstorms': weather_day_partly_sunny_thunderstormsComponent,
  'weather-day-partly-sunny': weather_day_partly_sunnyComponent,
  'weather-day-sunny-color': weather_day_sunny_colorComponent,
  'weather-day-sunny': weather_day_sunnyComponent,
  'weather-night-color': weather_night_colorComponent,
  'weather-night-mostly-cloudy-color': weather_night_mostly_cloudy_colorComponent,
  'weather-night-mostly-cloudy': weather_night_mostly_cloudyComponent,
  'weather-night-partly-cloudy-color': weather_night_partly_cloudy_colorComponent,
  'weather-night-partly-cloudy-flurries-color': weather_night_partly_cloudy_flurries_colorComponent,
  'weather-night-partly-cloudy-flurries': weather_night_partly_cloudy_flurriesComponent,
  'weather-night-partly-cloudy-showers-color': weather_night_partly_cloudy_showers_colorComponent,
  'weather-night-partly-cloudy-showers': weather_night_partly_cloudy_showersComponent,
  'weather-night-partly-cloudy-thunderstorms-color':
    weather_night_partly_cloudy_thunderstorms_colorComponent,
  'weather-night-partly-cloudy-thunderstorms': weather_night_partly_cloudy_thunderstormsComponent,
  'weather-night-partly-cloudy': weather_night_partly_cloudyComponent,
  'weather-night-snowy-color': weather_night_snowy_colorComponent,
  'weather-night-snowy': weather_night_snowyComponent,
  'weather-night-wintry-mix-color': weather_night_wintry_mix_colorComponent,
  'weather-night-wintry-mix': weather_night_wintry_mixComponent,
  'weather-night': weather_nightComponent,
  website: websiteComponent,
  'world-filled': world_filledComponent,
  world: worldComponent,
  'zoom-in': zoom_inComponent,
  'zoom-out': zoom_outComponent,
};
