import type { ComponentType } from 'react';
import type { IconWrapperProps } from '@/components/Icon/Icon.types';
import {
  AvatarIcon,
  AvatarFilledIcon,
  BookmarkIcon,
  BookmarkFilledIcon,
  CameraIcon,
  CameraFilledIcon,
  CategoryBusinessIcon,
  CategoryBusinessFilledIcon,
  CategoryLocalIcon,
  CategoryLocalFilledIcon,
  CategoryObituariesIcon,
  CategoryObituariesFilledIcon,
  CategoryOpinionIcon,
  CategoryOpinionFilledIcon,
  CategoryPoliticsIcon,
  CategoryPoliticsFilledIcon,
  CategorySportsIcon,
  CategorySportsFilledIcon,
  CategoryVariety01Icon,
  CategoryVariety01FilledIcon,
  CategoryVariety02Icon,
  CategoryVariety02FilledIcon,
  CategoryWorldIcon,
  CategoryWorldFilledIcon,
  ErrorIcon,
  ErrorFilledIcon,
  FlagIcon,
  FlagFilledIcon,
  HeadphonesIcon,
  HeadphonesFilledIcon,
  HelpIcon,
  HelpFilledIcon,
  HomeIcon,
  HomeFilledIcon,
  InformationIcon,
  InformationFilledIcon,
  LocationIcon,
  LocationFilledIcon,
  LockIcon,
  LockFilledIcon,
  MicrophoneIcon,
  MicrophoneFilledIcon,
  NotificationIcon,
  NotificationFilledIcon,
  PauseIcon,
  PauseFilledIcon,
  PlayIcon,
  PlayFilledIcon,
  SectionIcon,
  SectionFilledIcon,
  SendIcon,
  SendFilledIcon,
  SettingsIcon,
  SettingsFilledIcon,
  StarIcon,
  StarFilledIcon,
  ThumbsDownIcon,
  ThumbsDownFilledIcon,
  ThumbsUpIcon,
  ThumbsUpFilledIcon,
  VideoIcon,
  VideoFilledIcon,
  VolumeMuteIcon,
  VolumeMuteFilledIcon,
  VolumeIcon,
  VolumeFilledIcon,
} from '@/icons';

/**
 * Outline icon → filled icon for UtilityButton toggle `active`. Add a row when a new `{name}` + `{name}-filled`
 * pair ships in `@/icons`.
 */
export const utilityButtonIconFilledVariant = new WeakMap<
  ComponentType<IconWrapperProps>,
  ComponentType<IconWrapperProps>
>([
  [AvatarIcon, AvatarFilledIcon],
  [BookmarkIcon, BookmarkFilledIcon],
  [CameraIcon, CameraFilledIcon],
  [CategoryBusinessIcon, CategoryBusinessFilledIcon],
  [CategoryLocalIcon, CategoryLocalFilledIcon],
  [CategoryObituariesIcon, CategoryObituariesFilledIcon],
  [CategoryOpinionIcon, CategoryOpinionFilledIcon],
  [CategoryPoliticsIcon, CategoryPoliticsFilledIcon],
  [CategorySportsIcon, CategorySportsFilledIcon],
  [CategoryVariety01Icon, CategoryVariety01FilledIcon],
  [CategoryVariety02Icon, CategoryVariety02FilledIcon],
  [CategoryWorldIcon, CategoryWorldFilledIcon],
  [ErrorIcon, ErrorFilledIcon],
  [FlagIcon, FlagFilledIcon],
  [HeadphonesIcon, HeadphonesFilledIcon],
  [HelpIcon, HelpFilledIcon],
  [HomeIcon, HomeFilledIcon],
  [InformationIcon, InformationFilledIcon],
  [LocationIcon, LocationFilledIcon],
  [LockIcon, LockFilledIcon],
  [MicrophoneIcon, MicrophoneFilledIcon],
  [NotificationIcon, NotificationFilledIcon],
  [PauseIcon, PauseFilledIcon],
  [PlayIcon, PlayFilledIcon],
  [SectionIcon, SectionFilledIcon],
  [SendIcon, SendFilledIcon],
  [SettingsIcon, SettingsFilledIcon],
  [StarIcon, StarFilledIcon],
  [ThumbsDownIcon, ThumbsDownFilledIcon],
  [ThumbsUpIcon, ThumbsUpFilledIcon],
  [VideoIcon, VideoFilledIcon],
  [VolumeMuteIcon, VolumeMuteFilledIcon],
  [VolumeIcon, VolumeFilledIcon],
]);
