import type { ComponentType } from 'react';
import type { IconWrapperProps } from '@/components/Icon/Icon.types';
import {
  AvatarIcon,
  AvatarFilledIcon,
  BookmarkIcon,
  BookmarkFilledIcon,
  BusinessIcon,
  BusinessFilledIcon,
  CameraIcon,
  CameraFilledIcon,
  ErrorIcon,
  ErrorFilledIcon,
  FlagIcon,
  FlagFilledIcon,
  ForwardIcon,
  ForwardFilledIcon,
  HeadphonesIcon,
  HeadphonesFilledIcon,
  HelpIcon,
  HelpFilledIcon,
  HomeIcon,
  HomeFilledIcon,
  InformationIcon,
  InformationFilledIcon,
  Local01Icon,
  Local01FilledIcon,
  Local02Icon,
  Local02FilledIcon,
  LocationIcon,
  LocationFilledIcon,
  LockIcon,
  LockFilledIcon,
  MicrophoneIcon,
  MicrophoneFilledIcon,
  NotificationIcon,
  NotificationFilledIcon,
  ObituariesIcon,
  ObituariesFilledIcon,
  OpinionIcon,
  OpinionFilledIcon,
  PauseIcon,
  PauseFilledIcon,
  PlayIcon,
  PlayFilledIcon,
  PoliticsIcon,
  PoliticsFilledIcon,
  SectionIcon,
  SectionFilledIcon,
  SendIcon,
  SendFilledIcon,
  SettingsIcon,
  SettingsFilledIcon,
  ShootingStarDownRightIcon,
  ShootingStarDownRightFilledIcon,
  SpeechIcon,
  SpeechFilledIcon,
  SportsRosterIcon,
  SportsRosterFilledIcon,
  SportsIcon,
  SportsFilledIcon,
  StarIcon,
  StarFilledIcon,
  ThumbsDownIcon,
  ThumbsDownFilledIcon,
  ThumbsUpIcon,
  ThumbsUpFilledIcon,
  TombstoneIcon,
  TombstoneFilledIcon,
  Variety01Icon,
  Variety01FilledIcon,
  Variety02Icon,
  Variety02FilledIcon,
  VideoIcon,
  VideoFilledIcon,
  VolumeMuteIcon,
  VolumeMuteFilledIcon,
  VolumeIcon,
  VolumeFilledIcon,
  WorldIcon,
  WorldFilledIcon,
} from '@/icons';

/**
 * Outline icon → filled icon for UtilityButton toggle `active`. Add a row when a new `{name}` + `{name}-filled`
 * pair ships in `@/icons`.
 */
export const utilityButtonIconFilledVariant = new WeakMap<
  ComponentType<IconWrapperProps>,
  ComponentType<IconWrapperProps>
>([
  [AvatarIcon, AvatarFilledIcon],
  [BookmarkIcon, BookmarkFilledIcon],
  [BusinessIcon, BusinessFilledIcon],
  [CameraIcon, CameraFilledIcon],
  [ErrorIcon, ErrorFilledIcon],
  [FlagIcon, FlagFilledIcon],
  [ForwardIcon, ForwardFilledIcon],
  [HeadphonesIcon, HeadphonesFilledIcon],
  [HelpIcon, HelpFilledIcon],
  [HomeIcon, HomeFilledIcon],
  [InformationIcon, InformationFilledIcon],
  [Local01Icon, Local01FilledIcon],
  [Local02Icon, Local02FilledIcon],
  [LocationIcon, LocationFilledIcon],
  [LockIcon, LockFilledIcon],
  [MicrophoneIcon, MicrophoneFilledIcon],
  [NotificationIcon, NotificationFilledIcon],
  [ObituariesIcon, ObituariesFilledIcon],
  [OpinionIcon, OpinionFilledIcon],
  [PauseIcon, PauseFilledIcon],
  [PlayIcon, PlayFilledIcon],
  [PoliticsIcon, PoliticsFilledIcon],
  [SectionIcon, SectionFilledIcon],
  [SendIcon, SendFilledIcon],
  [SettingsIcon, SettingsFilledIcon],
  [ShootingStarDownRightIcon, ShootingStarDownRightFilledIcon],
  [SpeechIcon, SpeechFilledIcon],
  [SportsRosterIcon, SportsRosterFilledIcon],
  [SportsIcon, SportsFilledIcon],
  [StarIcon, StarFilledIcon],
  [ThumbsDownIcon, ThumbsDownFilledIcon],
  [ThumbsUpIcon, ThumbsUpFilledIcon],
  [TombstoneIcon, TombstoneFilledIcon],
  [Variety01Icon, Variety01FilledIcon],
  [Variety02Icon, Variety02FilledIcon],
  [VideoIcon, VideoFilledIcon],
  [VolumeMuteIcon, VolumeMuteFilledIcon],
  [VolumeIcon, VolumeFilledIcon],
  [WorldIcon, WorldFilledIcon],
]);
