/**
 * Type declarations for mobile typography tokens.
 * These files are generated by `yarn tokens` and live in dist/mobile/typography/.
 * The @mobile/typography alias is configured in vite.native.config.ts for the build.
 */
declare module '@mobile/typography/startribune-typography.js' {
  const typography: {
    articleQuoteSmall?: Record<string, unknown>;
    articleQuoteLarge?: Record<string, unknown>;
  };
  export default typography;
}

declare module '@mobile/typography/varsity-typography.js' {
  const typography: {
    articleQuoteSmall?: Record<string, unknown>;
    articleQuoteLarge?: Record<string, unknown>;
  };
  export default typography;
}
