name: Visual Regression

on:
  workflow_call:
  pull_request:
    branches: [main, 'release/**']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Check for component changes
    runs-on: ubuntu-latest
    outputs:
      uiChanged: ${{ steps.changes.outputs.ui }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            ui:
              - 'packages/design-system/src/**/*.stories.ts'
              - 'packages/design-system/src/**/*.stories.tsx'
              - 'packages/design-system/.storybook/**/*'

  chromatic:
    name: Run visual tests
    needs: changes
    if: needs.changes.outputs.uiChanged == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Node environment
        uses: ./.github/actions/configure-workflow-node-environment
      - name: Run Chromatic
        uses: chromaui/action@v13
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          autoAcceptChanges: main
          workingDir: packages/design-system
