/**
 * Auto-generated by `yarn tokens`. Do not edit manually.
 * Re-run `yarn tokens` to regenerate after token changes.
 *
 * Internal use only — provides type-checking and autocomplete for developers
 * authoring native components in this repo. This file is NOT published to npm
 * and is never seen by consuming apps.
 *
 * This file has NO top-level import/export so it remains a global ambient
 * declaration file. The 'declare module' blocks are automatically available
 * to all TypeScript files without explicit import.
 */
type TextStyle = import('react-native').TextStyle;

interface StartribuneTypography {
  typographyArticleBodyBold: TextStyle;
  typographyArticleBodyBoldItalic: TextStyle;
  typographyArticleBodyDropcap: TextStyle;
  typographyArticleBodyH1: TextStyle;
  typographyArticleBodyH2: TextStyle;
  typographyArticleBodyH3: TextStyle;
  typographyArticleBodyH4: TextStyle;
  typographyArticleBodyH5: TextStyle;
  typographyArticleBodyH6: TextStyle;
  typographyArticleBodyItalic: TextStyle;
  typographyArticleBodyLink: TextStyle;
  typographyArticleBodyRegular: TextStyle;
  typographyArticleBodySponsoredH1: TextStyle;
  typographyArticleBodySponsoredH2: TextStyle;
  typographyArticleBodySponsoredH3: TextStyle;
  typographyArticleBodySponsoredH4: TextStyle;
  typographyArticleBodySponsoredH5: TextStyle;
  typographyArticleBodySponsoredH6: TextStyle;
  typographyArticleBodySponsoredItalic: TextStyle;
  typographyArticleBodySponsoredLink: TextStyle;
  typographyArticleBodySponsoredRegular: TextStyle;
  typographyArticleBodySponsoredSemibold: TextStyle;
  typographyArticleBodySponsoredSemiboldItalic: TextStyle;
  typographyArticleQuoteLarge: TextStyle;
  typographyArticleQuoteSmall: TextStyle;
  typographyEditorialEnterpriseH1: TextStyle;
  typographyEditorialEnterpriseH2: TextStyle;
  typographyEditorialEnterpriseH3: TextStyle;
  typographyEditorialEnterpriseH4: TextStyle;
  typographyEditorialEnterpriseH5: TextStyle;
  typographyEditorialEnterpriseH6: TextStyle;
  typographyEditorialNewsH1: TextStyle;
  typographyEditorialNewsH2: TextStyle;
  typographyEditorialNewsH3: TextStyle;
  typographyEditorialNewsH4: TextStyle;
  typographyEditorialNewsH5: TextStyle;
  typographyEditorialNewsH6: TextStyle;
  typographyEditorialNonNewsH1: TextStyle;
  typographyEditorialNonNewsH2: TextStyle;
  typographyEditorialNonNewsH3: TextStyle;
  typographyEditorialNonNewsH4: TextStyle;
  typographyEditorialNonNewsH5: TextStyle;
  typographyEditorialNonNewsH6: TextStyle;
  typographyEditorialOpinionH1: TextStyle;
  typographyEditorialOpinionH2: TextStyle;
  typographyEditorialOpinionH3: TextStyle;
  typographyEditorialOpinionH4: TextStyle;
  typographyEditorialOpinionH5: TextStyle;
  typographyEditorialOpinionH6: TextStyle;
  typographyEditorialSponsoredH1: TextStyle;
  typographyEditorialSponsoredH2: TextStyle;
  typographyEditorialSponsoredH3: TextStyle;
  typographyEditorialSponsoredH4: TextStyle;
  typographyEditorialSponsoredH5: TextStyle;
  typographyEditorialSponsoredH6: TextStyle;
  typographyEditorialTextBoldLarge: TextStyle;
  typographyEditorialTextBoldMedium: TextStyle;
  typographyEditorialTextBoldSmall: TextStyle;
  typographyEditorialTextBoldXLarge: TextStyle;
  typographyEditorialTextBoldXSmall: TextStyle;
  typographyEditorialTextBoldXxSmall: TextStyle;
  typographyEditorialTextRegularLarge: TextStyle;
  typographyEditorialTextRegularMedium: TextStyle;
  typographyEditorialTextRegularSmall: TextStyle;
  typographyEditorialTextRegularXLarge: TextStyle;
  typographyEditorialTextRegularXSmall: TextStyle;
  typographyEditorialTextRegularXxSmall: TextStyle;
  typographyEditorialTextSponsoredBoldLarge: TextStyle;
  typographyEditorialTextSponsoredBoldMedium: TextStyle;
  typographyEditorialTextSponsoredBoldSmall: TextStyle;
  typographyEditorialTextSponsoredBoldXLarge: TextStyle;
  typographyEditorialTextSponsoredBoldXSmall: TextStyle;
  typographyEditorialTextSponsoredBoldXxSmall: TextStyle;
  typographyEditorialTextSponsoredRegularLarge: TextStyle;
  typographyEditorialTextSponsoredRegularMedium: TextStyle;
  typographyEditorialTextSponsoredRegularSmall: TextStyle;
  typographyEditorialTextSponsoredRegularXLarge: TextStyle;
  typographyEditorialTextSponsoredRegularXSmall: TextStyle;
  typographyEditorialTextSponsoredRegularXxSmall: TextStyle;
  typographyUtilityLabelLarge: TextStyle;
  typographyUtilityLabelLargeCaps: TextStyle;
  typographyUtilityLabelMedium: TextStyle;
  typographyUtilityLabelMediumCaps: TextStyle;
  typographyUtilityLabelSemiboldLarge: TextStyle;
  typographyUtilityLabelSemiboldLargeCaps: TextStyle;
  typographyUtilityLabelSemiboldMedium: TextStyle;
  typographyUtilityLabelSemiboldMediumCaps: TextStyle;
  typographyUtilityLabelSemiboldSmall: TextStyle;
  typographyUtilityLabelSemiboldSmallCaps: TextStyle;
  typographyUtilityLabelSmall: TextStyle;
  typographyUtilityLabelSmallCaps: TextStyle;
  typographyUtilityPageH1: TextStyle;
  typographyUtilityPageH2: TextStyle;
  typographyUtilityPageH3: TextStyle;
  typographyUtilityPageH4: TextStyle;
  typographyUtilitySectionH1: TextStyle;
  typographyUtilitySectionH2: TextStyle;
  typographyUtilitySectionH3: TextStyle;
  typographyUtilitySectionH4: TextStyle;
  typographyUtilitySectionH5: TextStyle;
  typographyUtilitySectionH6: TextStyle;
  typographyUtilityTextBoldLarge: TextStyle;
  typographyUtilityTextBoldMedium: TextStyle;
  typographyUtilityTextBoldSmall: TextStyle;
  typographyUtilityTextBoldXLarge: TextStyle;
  typographyUtilityTextBoldXSmall: TextStyle;
  typographyUtilityTextBoldXxSmall: TextStyle;
  typographyUtilityTextItalicLarge: TextStyle;
  typographyUtilityTextItalicMedium: TextStyle;
  typographyUtilityTextItalicSmall: TextStyle;
  typographyUtilityTextItalicXLarge: TextStyle;
  typographyUtilityTextItalicXSmall: TextStyle;
  typographyUtilityTextItalicXxSmall: TextStyle;
  typographyUtilityTextMediumLarge: TextStyle;
  typographyUtilityTextMediumMedium: TextStyle;
  typographyUtilityTextMediumSmall: TextStyle;
  typographyUtilityTextMediumXLarge: TextStyle;
  typographyUtilityTextMediumXSmall: TextStyle;
  typographyUtilityTextMediumXxSmall: TextStyle;
  typographyUtilityTextRegularLarge: TextStyle;
  typographyUtilityTextRegularMedium: TextStyle;
  typographyUtilityTextRegularSmall: TextStyle;
  typographyUtilityTextRegularXLarge: TextStyle;
  typographyUtilityTextRegularXSmall: TextStyle;
  typographyUtilityTextRegularXxSmall: TextStyle;
  typographyUtilityTextSemiboldLarge: TextStyle;
  typographyUtilityTextSemiboldMedium: TextStyle;
  typographyUtilityTextSemiboldSmall: TextStyle;
  typographyUtilityTextSemiboldXLarge: TextStyle;
  typographyUtilityTextSemiboldXSmall: TextStyle;
  typographyUtilityTextSemiboldXxSmall: TextStyle;
}

interface VarsityTypography {
  typographyArticleBodyBold: TextStyle;
  typographyArticleBodyBoldItalic: TextStyle;
  typographyArticleBodyDropcap: TextStyle;
  typographyArticleBodyH1: TextStyle;
  typographyArticleBodyH2: TextStyle;
  typographyArticleBodyH3: TextStyle;
  typographyArticleBodyH4: TextStyle;
  typographyArticleBodyH5: TextStyle;
  typographyArticleBodyH6: TextStyle;
  typographyArticleBodyItalic: TextStyle;
  typographyArticleBodyLink: TextStyle;
  typographyArticleBodyRegular: TextStyle;
  typographyArticleQuoteLarge: TextStyle;
  typographyArticleQuoteSmall: TextStyle;
  typographyEditorialNewsH1: TextStyle;
  typographyEditorialNewsH2: TextStyle;
  typographyEditorialNewsH3: TextStyle;
  typographyEditorialNewsH4: TextStyle;
  typographyEditorialNewsH5: TextStyle;
  typographyEditorialNewsH6: TextStyle;
  typographyEditorialOpinionH1: TextStyle;
  typographyEditorialOpinionH2: TextStyle;
  typographyEditorialOpinionH3: TextStyle;
  typographyEditorialOpinionH4: TextStyle;
  typographyEditorialOpinionH5: TextStyle;
  typographyEditorialOpinionH6: TextStyle;
  typographyEditorialTextBoldLarge: TextStyle;
  typographyEditorialTextBoldMedium: TextStyle;
  typographyEditorialTextBoldSmall: TextStyle;
  typographyEditorialTextBoldXLarge: TextStyle;
  typographyEditorialTextBoldXSmall: TextStyle;
  typographyEditorialTextBoldXxSmall: TextStyle;
  typographyEditorialTextRegularLarge: TextStyle;
  typographyEditorialTextRegularMedium: TextStyle;
  typographyEditorialTextRegularSmall: TextStyle;
  typographyEditorialTextRegularXLarge: TextStyle;
  typographyEditorialTextRegularXSmall: TextStyle;
  typographyEditorialTextRegularXxSmall: TextStyle;
  typographyUtilityLabelLarge: TextStyle;
  typographyUtilityLabelLargeCaps: TextStyle;
  typographyUtilityLabelMedium: TextStyle;
  typographyUtilityLabelMediumCaps: TextStyle;
  typographyUtilityLabelSemiboldLarge: TextStyle;
  typographyUtilityLabelSemiboldLargeCaps: TextStyle;
  typographyUtilityLabelSemiboldMedium: TextStyle;
  typographyUtilityLabelSemiboldMediumCaps: TextStyle;
  typographyUtilityLabelSemiboldSmall: TextStyle;
  typographyUtilityLabelSemiboldSmallCaps: TextStyle;
  typographyUtilityLabelSmall: TextStyle;
  typographyUtilityLabelSmallCaps: TextStyle;
  typographyUtilityPageH1: TextStyle;
  typographyUtilityPageH2: TextStyle;
  typographyUtilityPageH3: TextStyle;
  typographyUtilityPageH4: TextStyle;
  typographyUtilitySectionH1: TextStyle;
  typographyUtilitySectionH2: TextStyle;
  typographyUtilitySectionH3: TextStyle;
  typographyUtilitySectionH4: TextStyle;
  typographyUtilitySectionH5: TextStyle;
  typographyUtilitySectionH6: TextStyle;
  typographyUtilityTextBoldLarge: TextStyle;
  typographyUtilityTextBoldMedium: TextStyle;
  typographyUtilityTextBoldSmall: TextStyle;
  typographyUtilityTextBoldXLarge: TextStyle;
  typographyUtilityTextBoldXSmall: TextStyle;
  typographyUtilityTextBoldXxSmall: TextStyle;
  typographyUtilityTextItalicLarge: TextStyle;
  typographyUtilityTextItalicMedium: TextStyle;
  typographyUtilityTextItalicSmall: TextStyle;
  typographyUtilityTextItalicXLarge: TextStyle;
  typographyUtilityTextItalicXSmall: TextStyle;
  typographyUtilityTextItalicXxSmall: TextStyle;
  typographyUtilityTextMediumLarge: TextStyle;
  typographyUtilityTextMediumMedium: TextStyle;
  typographyUtilityTextMediumSmall: TextStyle;
  typographyUtilityTextMediumXLarge: TextStyle;
  typographyUtilityTextMediumXSmall: TextStyle;
  typographyUtilityTextMediumXxSmall: TextStyle;
  typographyUtilityTextRegularLarge: TextStyle;
  typographyUtilityTextRegularMedium: TextStyle;
  typographyUtilityTextRegularSmall: TextStyle;
  typographyUtilityTextRegularXLarge: TextStyle;
  typographyUtilityTextRegularXSmall: TextStyle;
  typographyUtilityTextRegularXxSmall: TextStyle;
  typographyUtilityTextSemiboldLarge: TextStyle;
  typographyUtilityTextSemiboldMedium: TextStyle;
  typographyUtilityTextSemiboldSmall: TextStyle;
  typographyUtilityTextSemiboldXLarge: TextStyle;
  typographyUtilityTextSemiboldXSmall: TextStyle;
  typographyUtilityTextSemiboldXxSmall: TextStyle;
}

type TypographyTokens = StartribuneTypography | VarsityTypography;

declare module '@mobile/typography/startribune-typography.js' {
  const typography: StartribuneTypography;
  export = typography;
}

declare module '@mobile/typography/varsity-typography.js' {
  const typography: VarsityTypography;
  export = typography;
}
